interuss/dss

.editorconfig

This will automatically configure many editors to use two space indents, making it easier for people to contribute who normally use four spaces for Python code.

Add .editorconfig with two-space indents to match code style

---

datanode/docker/Dockerfile_storageapi
datanode/docker/README.md
datanode/docker/docker-compose_pybasetest.yaml
datanode/docker/docker-compose_storageapitest.yaml
datanode/src/storage_api.py

Adds a flag to turn on ad-hoc SSL support in the web app which turns all endpoints into https.
Also fixes the two docker compose yaml files to use the fully-qualified image names.

Add ad-hoc SSL support

---

datanode/docker/datanode_entrypoint.sh
datanode/src/README.md
datanode/src/storage_api.py
datanode/src/storage_api_test.py
datanode/src/storage_interface.py
datanode/src/storage_interface_test.py
datanode/src/uss_metadata.py

Added uss_metadata.py to separate logic from data structure for better maintenance,
Updated docker script to 0.0.0.0 out local servers as required for Zookeeper,
Slippy errors fixe, input standardized to CSV of lat,lon, and output more JSON friendly,
Date parsing is more robust, handling timezone aware and timezone unaware dates,
Updated OAuth public key parsing to handle the way they are formatted as environment variables,
Updated version to 1.0.1 to cover changes in slippy api, Swaggerhub updates in progress.

Bug fixes for slippy, dates, and OAuth key

---

datanode/src/storage_interface.py
datanode/src/storage_interface_test.py
datanode/src/uss_metadata.py

Underlying changes for supporting multiple grids, this pull request has a few changes:
- Change zookeeper interface to use version instead of locks for writing (sync_token still validated)
- Change test cases to be more readable
- Add zoom, x, and y in the metadata response (in each operator, fixes #32 )
- get, set, and delete operations for multiple grids using zookeeper transaction/commit functions and zookeeper version numbers to quickly update and rollback if needed
- Started progress on using proper error handling in storage_interface.py
Only API changes are on Swaggerhub (zoom, x, y in operator response). Still internally version 1.0.2
https://app.swaggerhub.com/apis/InterUSS_Platform/data_node_api/1.1.0#/
Next change will be the storage API to support multiple grids using a new …

Storage interface changes to support multi-grid

---

datanode/docker/Dockerfile_storageapi
datanode/docker/README.md
datanode/docker/docker-compose.yaml
datanode/src/slippy_util.py
datanode/src/slippy_util_test.py
datanode/src/storage_api.py
datanode/src/storage_api_test.py
datanode/src/storage_interface.py
datanode/src/storage_interface_test.py

Added endpoint /GridCellsMetaData to support multiple grid changes via a set of points, a path or an enclosed polygon. This fixes Issue #35 .
Swaggerhub is updated as well as the server that drives it, available here to test:
https://app.swaggerhub.com/apis/InterUSS_Platform/data_node_api/1.1.0

API Changes to support multi-grid GET/PUT/DEL

---

datanode/src/storage_api.py
datanode/src/storage_api_test.py

The assumptions about how data was carried in UVR web requests were incorrect; this PR fixes them.  Now, the body must contain only a UVR JSON object and it cannot be provided by other means (query, form).
This PR also fixes an issue where an invalid response would be returned in error cases involving missing uss_id or missing JSON (instead, a 500 error would be returned).

Fix UVR data carriage

---

datanode/tools/client_tools.py
datanode/tools/get_token
datanode/tools/monitor
datanode/tools/report
datanode/tools/reports.py

This PR adds three tools to help with real-time monitoring, like during a shakedown.
```report``` reports the instantaneous status of Operators in a node.
```monitor``` polls a node and reports changes in Operators in that node.
```get_token``` retrieves an OAuth token, and can be used to avoid repeated calls to the OAuth server when using ```report```.

Add real-time monitoring tools

---

datanode/src/storage_api.py
datanode/src/uss_metadata.py

When 4.0.3 was deployed to servers still using previous-version metadata, it would fail when trying to parse that old metadata which does not match the current spec.  This PR provides backwards compatibility by tolerating missing 4.0.3 fields when parsing.

Only iterate through JSON 'uvr' field if it is present

---

datanode/src/storage_api.py
datanode/src/storage_api_test.py
datanode/src/storage_interface.py
datanode/src/storage_interface_test.py
datanode/src/uss_metadata.py

This PR implements the API changes for [public portal 1.1.0](https://app.swaggerhub.com/apis/InterUSS_Platform/data_node_api/publicportal1.1.0) per issue #50, which mainly consist of adding two fields to each operator entry in GridCellMetaData: `public_portal_endpoint` and `flight_info_endpoint`.
Accompanying the addition of these fields are slightly more tolerant acceptance criteria.  Now, a `sync_token` is only required when specifying an `operation_endpoint`, implying that the participant has deconflicted a flight.  A participant may create an entry in one or more grid cells without a `sync_token` if specifying `public_portal_endpoint` and/or `flight_info_endpoint` but not an `operation_endpoint`.  At least one endpoint must be specified (or else there would be no point in populating …

Implement public portal API changes

---

datanode/src/storage_api.py
datanode/src/storage_api_test.py
datanode/src/storage_interface.py
datanode/src/test_utils.py
datanode/src/uvrs.py

This PR updates the UVR schema to remove `origin` and `originator_id` and add `uss_name` according to [this link](https://github.com/nasa/utm-apis/blob/0435188d755c6685c75c10eb82ce0164a7e6a51f/utm-domains/utm-domain-commons.yaml#L1476).  It also adds validation to ensure that all required UVR fields (including `uss_name`) are specified, and then checks whether the `uss_name` provided in the UVR matches the ID in the access token (instead of overwriting `originator_id` with the ID in the access token).
Also, OTHER is added to `cause` enum values, and additional validation is added to `permitted_uas`.

Update UVR schema and validate required fields

---

authserver/docker/Dockerfile_authreverseproxy
authserver/docker/Dockerfile_authserver
authserver/docker/README.md
authserver/docker/docker-compose.yaml
authserver/docker/nginx_entrypoint.sh
authserver/src/auth_server.py
authserver/src/auth_server_test.py

This PR adds a simple authorization server that generates access tokens to be used to access an InterUSS Platform data node.  The server itself (```auth_server.py```) uses a private key to generate a JWT access token for a user from a provided roster of (username, hashed password, scopes) after authorizing with Basic authorization, as well as serving the public key.  All transactions are over HTTP which makes the bare server unsuitable for standalone use; instead, a docker-compose system adds an nginx reverse proxy in front of the auth server to wrap all transport in HTTPS.
This version grants all available scopes, ignoring whatever scopes may have been requested.  A future version will grant only the requested scope(s).

Add auth server

---

assets/swaggerhub_api.yaml
datanode/docker/Dockerfile_storageapi
datanode/docker/README.md
datanode/src/storage_api.py
datanode/src/storage_interface.py
datanode/src/uss_metadata.py
datanode/src/uvrs.py

This PR modifies the updated UVR schema behavior to store in the legacy format (so older clients/grid data aren't confused), but expose the new format in the API.  It also updates deployment instructions and the version tag.

Fix backwards compatibility for UVRs on storage side only

---

authserver/docker/docker-compose.yaml
authserver/docker/node.sh
datanode/docker/docker-compose.yaml
datanode/docker/node.sh

This PR adds `node.sh` scripts for both the auth server and data node that, after being filled in with server-specific information, can be used to bring up or down the respective production system in one command.  It also adds `restart: always` to make the docker containers more resilient.

Add deployment tools

---

datanode/docker/Dockerfile_reverseproxy
datanode/docker/README.md
datanode/docker/docker-compose.yaml
datanode/docker/docker-compose_localssl.yaml
datanode/docker/nginx_entrypoint.sh
datanode/docker/node.sh
datanode/src/updating.md

The PR adds a `node.sh` quick deployment script and documentation.  It also updates the docker-compose files to allow specific naming of the SSL certificate files, and adds `restart: always` flags for resilience (mirroring changes in publicportal branch).
There are no changes to functionality outside the slight docker-compose alterations.

Update TCL4 deployment information

---

datanode/src/storage_api.py
datanode/src/storage_api_test.py
datanode/src/storage_interface.py

This PR improves the `status` endpoint to include more information that is likely to indicate why a node is in poor health including disk usage (if logs have filled up the disk) and connection to the Zookeeper server.

Augment status endpoint

---

datanode/docker/Dockerfile_reverseproxy
datanode/docker/Dockerfile_storageapi
datanode/docker/README.md
datanode/docker/docker-compose.yaml
datanode/docker/docker-compose_storageapitest.yaml
datanode/docker/nginx_entrypoint.sh

Because the data node authorizes with a reusable access token in the plaintext request header, it is insecure to allow access to the data node via HTTP.  This PR removes HTTP access to the data node via the nginx layer, leaving only HTTPS.
HTTP access to the data node is still possible in development or for special-case configurations not requiring security by exposing the INTERUSS_API_PORT in the storage_api container, or bringing up the system described in docker-compose_storageapitest.yaml rather than the full system in docker-compose.yaml.

Remove HTTP access from nginx configuration

---

datanode/tools/client_tools.py
datanode/tools/monitor
datanode/tools/report

This PR extends the TCL4 diagnostic `monitor` tool to capture operation details in addition to the grid summaries it previously captured.  To do this, it creates a TokenManager to automatically retrieve and appropriately cache tokens with different scopes, and provides a differently-scoped access token to retrieve operations from USS's than to retrieve the grid state.
This tool was tested successfully during a UPP shakedown.

Record operation details from diagnostic logging tool

---

datanode/docker/docker-compose.yaml

The latest version of the zookeeper image is not backwards-compatible with our implementation; we must explicitly refer to 3.4 to maintain functionality.

Add explicit zookeeper:3.4 tag in docker config

---

datanode/src/storage_interface.py
datanode/src/storage_interface_test.py

This PR aims to replace zookeeper for cockroachdb for testing purposes. This is a WIP, and meant to gather data and feedback. Important remarks:
- I started over with a very simple database schema, pretty much emulating a KV-store.
- Table creation is done in the ctor of `USSMetadataManager`. Not optimal, but I was hesitant to introduce full-blown schema migration support in the scope of this PR. 
- Tile coordinates still use slippy, and the original pathing is kept in place.
- While zookeeper distinguishes transaction ids and versions, I naively used the transaction timestamp for both in the case of cockroach. Tests seem to be happy, not sure if calling code expects integers, though. If so, we could consider hashing the transaction timestamps (slightly ugly and not monotonically …

Replace zookeeper with cockroachdb for testing purposes

---

datanode/src/README.md
datanode/src/storage_api.py
datanode/src/storage_interface.py

This is a WIP right now, accumulating documentation (adjustments) for running an instance of the API talking to one or many cockroach DB nodes. Open work items:

Adjust docs for cockroach

---

assets/swaggerhub_api.yaml
datanode/src/authorization.py
datanode/src/authorization_test.py
datanode/src/storage_api.py
datanode/src/storage_api_test.py

This PR factors out _ValidateAccessToken into an `authorization` module which allows not only the existing solution of providing a single, global public key, but also a custom authorization configuration with multiple overlapping authorization providers and complex applicability specifications.
Additional `introspect` endpoints are added to help troubleshoot any issues that may arise due to complex custom configurations.
The way options are loaded in `storage_api.py` is modified somewhat to always use the ParseOptions method, which uses environment variables as defaults.  This happens to solve questions of whether a command line argument or environment variable would take precedence, but its primary purpose is to ensure that a global `auth` variable in `storage_api.py` is instantiated …

Add custom/area-based authorization

---

datanode/src/slippy_util.py

PEP 479 is enabled for all code in Python 3.7, meaning that StopIteration exceptions raised directly or indirectly in coroutines and generators are transformed into RuntimeError exceptions.
This fix gets us one step closer to python 3 compatibility (at least for >=3.7 :pizza:).
I tested it with python 2.7 & 3.7

fix "RuntimeError: generator raised StopIteration" in python 3.7

---

README.md
doc.go

We are introducing a top-level `doc.go` such that `godoc.org/github.com/interuss/dss` picks up the package properly.

[docs] Fix nits and introduce top-level doc.go

---

cmds/dummy-oauth/main.go
monitoring/prober/conftest.py
pkg/dss/auth/auth.go
pkg/dss/auth/auth_test.go
pkg/dss/auth/claims.go

Makes the DSS reject token with missing Expiration and Issuer field #127 
In addition the standard mentions that the token cannot be valid for more than 1 hour into the future so we also check it and reject token are are given too wide of a window

Add Check for Token Issuer and Expiration

---

monitoring/prober/test_subscription_validation.py
pkg/dss/cockroach/subscriptions_test.go
pkg/dss/models/subscriptions.go
pkg/dss/server.go

Currently the DSS accepts Subscription PUTs even though the subscription duration is longer than 24hrs, but truncates it internally to 24hrs; which could be confusing to the caller. This checks for the duration and returns an Error with appropriate error message 
Issue: #154

Reject Subscription PUTS if longer than 24hrs

---

cmds/http-gateway/main.go
pkg/dss/geo/s2.go
pkg/dss/server.go
pkg/errors/errors.go
test/docker_e2e.sh

Since there was no direct mapping from grpc code to HTTP code
for 413 I had to replicate the entire method for handling GRPC
error code from the library just to do this.
Also fixed an annoying typo in docker_e2e.sh

Fix return code when searching large area

---

monitoring/prober/test_subscription_validation.py
pkg/dss/cockroach/subscriptions.go

1. SQL MAX statement returns NULL in the event there is no data, which triggers an error unable to convert nil to int even though there is simply no subscriptions
2. Test Subscription was too short lived, the cumulative time it takes to create 11 subscriptions sometimes take longer than the test subscription's life which expires and allows new subs to be created 
This now fixes the test_create_too_many_subs test flakiness

Fix issue with allowing too many subs

---

pkg/dss/cockroach/store_test.go

This flag.Parse is not necessary as go test already calls flags.Parse once, calling it again causes failure on local tests

Fix local test failure with double flag.Parse Call

---

monitoring/prober/test_isa_simple.py
monitoring/prober/test_subscription_simple.py
pkg/dss/cockroach/subscriptions_test.go
pkg/dss/models/models.go
pkg/dss/server.go
pkg/dss/server_test.go
test/interoperability/clients.py
test/interoperability/interop_test_suite.py

Interoperability test exposed that this was allowed in the DSS
while the specs states that Version is a required field
New behivior is to return Bad Request Error with proper message

Deletion of ISA and SUB were permitted w/o version

---

cmds/http-gateway/main.go

we should not forward the healthy call to grpcMux since it is not a valid method in the GRPC backend

Healthy is not part of GRPC backend

---

build/check_dss.sh
build/run-locally.sh
cmds/dummy-oauth/main.go

Also add check_dss.sh script to verify that the local DSS supports an example call.
Given the clarity difficulties of #171, this PR makes it even more clear what is happening in `run_locally.sh` and provides hints for what the user should do next to explore further, including a `check_dss.sh` script that makes an example call to the DSS.

Add clarity to run_locally.sh output

---

build/README.md
build/deploy/cockroachdb-auxilliary.libsonnet
build/deploy/examples/minimum.jsonnet
build/deploy/examples/prod_leaf.jsonnet
build/deploy/metadata_base.libsonnet

This isn't used anywhere, and it's not needed for any ops.
I'm leaving in some small comments below that reference that a user can do it if they choose to.

remove the external crdb loadbalancer as we don't need it

---

pkg/logging/logging.go
test/docker_e2e.sh

This PR renders the e2e test script more robust by:
* relying on `/usr/bin/env` to resolve the location of `bash`
* installing traps for `exit` and `sigint`
* not removing containers automatically to support gathering partial logs

Robustify e2e test script

---

build/dev/check_subs.sh
build/dev/run_locally.sh
cmds/grpc-backend/main.go
cmds/http-gateway/main.go
monitoring/prober/README.md
monitoring/prober/common.py
monitoring/prober/conftest.py
monitoring/prober/test_scd_subscriptions.py
pkg/dss/utm/models/models.go
pkg/dss/utm/models/subscriptions.go
pkg/dss/utm/server.go
pkg/dss/utm/store.go
test/docker_e2e.sh

This PR begins implementation of strategic conflict detection Subscription endpoints and the dummy Store.  This work passes all tests (including additional tests for new functionality), but is incomplete because currently, our processing chain does not parse string-based enums correctly.  Many of the test assertions are commented out because of this.  Also, the geographic translation is not yet performed as the existing translation logic will need to be factored into a generic routine that can be used both with RID volumes and SCD volumes.

Add Subscription support for dummy SCD Store and partial endpoint implementations

---

Makefile
go.mod
pkg/dss/scd/cockroach/doc.go
pkg/dss/scd/cockroach/store.go
pkg/dss/scd/cockroach/store_test.go
pkg/dss/scd/cockroach/subscriptions.go
pkg/dss/scd/cockroach/subscriptions_test.go
pkg/dss/scd/models/models.go
pkg/dss/scd/models/subscriptions.go
pkg/dss/scd/server.go
pkg/dss/scd/store.go

This PR:
* introduces an implementation of `scd.Store` talking to a `cockroach` DB, drawing heavy inspiration from the existing `rid.Store` CRDB implementation (read as: copy'n'pasted mostly and adjusted)
* adjusts models as required by the differing versioning schemes in `rid` and `scd`
* adjusts and occasionally simplifies the `scd.Server` implementation
* provides plenty of future opportunity to consolidate types and methods across `rid` and `scd`

Introduce scd cockroach store

---

monitoring/prober/scd/test_operations_simple.py
pkg/scd/operations_handler.go
pkg/scd/subscriptions_handler.go

This PR adds a number of tests to validate OVN visibility between different USSs when manipulating Operations and Operation-related Subscriptions.  It also adds a simple fix for an issue discovered.
It also adds tests for mutating Subscriptions in ways not allowed by their dependent Operations, but those tests are commented out until we validate Subscription changes with dependent Operations (in another PR).

Fix OVN visibility

---

monitoring/prober/conftest.py

Strategic conflict detection requires two client identities to access to the DSS to perform Operation tests.  Using the dummy OAuth is fine because tokens with different IDs can easily be requested.  However, the flags were not configured properly to use a non-dummy OAuth provider in the integration tests.  This PR fixes that issue, as originally identified by ANRA.

Fix flag names for second SCD test session authentication

---

cmds/grpc-backend/main.go
go.mod
go.sum
pkg/rid/cockroach/store.go
pkg/rid/cockroach/store_test.go

This is not meant to be a long term solution, but meant to hold until we have a supported schema migration pipeline. 
it also includes with example code of what it should be doing, if we had an external versioning system

Rudimentary schema version enforcement

---

monitoring/prober/rid/test_isa_expiry.py
pkg/rid/cockroach/identification_service_area.go
pkg/rid/cockroach/identification_service_area_test.go
pkg/rid/cockroach/store.go
pkg/rid/cockroach/store_test.go
pkg/rid/cockroach/subscriptions.go
pkg/rid/cockroach/subscriptions_test.go

RMW breaks if we don't return by ID when expired.

should always return by id, even if expired

---

build/deploy/cockroachdb.libsonnet

Max unavailable is not out for statefulsets yet https://github.com/kubernetes/kubernetes/issues/68397, and rolling update is arleady the default https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

Remove updateStrategy for crdb

---

monitoring/prober/scd/test_subscription_id_conversion.py
pkg/scd/store/cockroach/subscriptions.go

This PR fixes #314 by explicitly casting an int64 from the database to a uint64 before constructing an s2.CellID from it.

Fix Subscription cells lookup

---

monitoring/prober/scd/test_operation_special_cases.py
pkg/scd/operations_handler.go
pkg/scd/store/cockroach/operations.go
pkg/scd/store/cockroach/subscriptions.go

An SCD test started failing on master despite passing at merge time because a time was hardcoded into a test resource (based on an error report submitted by a user).  This caused an Operation to be created in the past, which may be acceptable in SCD.  However, when the system went to look up the implicit Subscription created for that Operation, it did not appear in the query because of the real-time constraint.  The PR fixes the test by removing the real-time constraint and adds a TODO to improve logic in a future PR.  It also fixes a latent bug where deleting a lone Operation may result in a 500.

Fix SCD test

---

monitoring/prober/conftest.py
monitoring/prober/scd/common.py
monitoring/prober/scd/test_subscription_queries.py
pkg/scd/store/cockroach/subscriptions.go
pkg/scd/store/store.go
pkg/scd/subscriptions_handler.go

This PR changes SearchSubscriptions to accept a Volume4D rather than a simple set of cells and owner.  This is done to move toward simpler Store operations that don't embed application logic (like checking the owner of Subscriptions) and therefore can be more easily combined into application-level operations and more easily mocked (while still testing all application logic).
A suite of Subscription query integration tests are added to verify functionality, and they also revealed an incorrect SQL query that has been corrected.

Use Volume4D in SearchSubscriptions

---

monitoring/prober/conftest.py
monitoring/prober/infrastructure.py
monitoring/prober/rid/common.py
monitoring/prober/rid/test_token_validation.py
monitoring/prober/scd/common.py
monitoring/prober/scd/test_operation_simple.py

Previously, our integration test suite almost always depended on the assumption that every token would be a super token, containing all scopes necessary to perform any action on the system.  This PR begins the process of making intended scopes more explicit and more customizable in tests.
The primary means by which this is accomplished are that 1) a new Session type is used which attaches an `auth` parameter to requests automatically according to an additional `scope` or `scopes` argument in each verb (`get`, `put`, etc) and 2) a test function decorator `default_scope` modifies each of the session inputs to that test function to default to the specified scope for the duration of that test function.
This PR also updates test_operation_simple.py to always explicitly specify scopes (using …

Add easy scope specification to integration test suite

---

pkg/scd/operations_handler.go
pkg/scd/repos/repos.go
pkg/scd/store/cockroach/operations.go
pkg/scd/store/cockroach/subscriptions.go
pkg/scd/subscriptions_handler.go

This PR extracts most application logic embedded in the SCD store/repo layer for Subscription repo actions as well as SearchOperations.  This allows us to move toward a simple CRUD store which allows simpler mocks that more realistically test the application logic checks and behavior currently embedded in the store implementation.
One functional change in this PR is that the Subscription count is no longer checked in SCD because there is no maximum Subscription count requirement in the SCD draft standard, and there is unlikely to be a maximum requirement because of implicit Subscriptions for Operations.

Simplify SCD repo APIs (Subscription + SearchOperations)

---

monitoring/prober/rid/test_isa_validation.py
monitoring/prober/scd/resources/op_request_4.json
monitoring/prober/scd/test_operation_special_cases.py
pkg/geo/s2.go
test/docker_e2e.sh

We were incorrectly calculating loop area with `(loop.Area() * earthAreaKm2) / 4.0 * math.Pi` instead of `(loop.Area() * earthAreaKm2) / (4.0 * math.Pi)`.  This PR fixes that bug.
It also adds a log file output for building the dummy OAuth image since that can take minutes and it would be valuable to have feedback there to confirm that the process wasn't stalled.

Fix incorrect area calculation

---

Makefile
build/deploy/db-schemas/defaultdb.libsonnet
build/deploy/db-schemas/defaultdb/000002_inverted_index.up.sql
build/deploy/db-schemas/defaultdb/000005_bump_version.down.sql
build/deploy/db-schemas/defaultdb/000005_bump_version.up.sql
build/deploy/examples/minimum/main.jsonnet
build/deploy/examples/prod/main.jsonnet
cmds/grpc-backend/main.go
pkg/cockroach/cockroach.go
pkg/rid/application/application_test.go
pkg/rid/store/cockroach/store.go
pkg/rid/store/cockroach/store_test.go
test/docker_e2e.sh

GRPC will now try to get the DB Schema Version and fail if the DB was not bootstrapped with the Schema Manager

Remove Bootstrapping Functionality from GRPC

---

Makefile
build/deploy/db-schemas/defaultdb.libsonnet
build/deploy/db-schemas/defaultdb/000006_add_writer_column.down.sql
build/deploy/db-schemas/defaultdb/000006_add_writer_column.up.sql
build/deploy/examples/minimum/main.jsonnet
build/deploy/examples/prod/main.jsonnet
test/docker_e2e.sh

Due to the nature of the how the DSS is setup with multiple companies owning a piece of the infrastructure and therefore multiple "GRPC Backend" server running, we've decided to make each instance be responsible for cleaning up its own garbage, therefore with every write to the the DB we need it to also put its name down as the writer so that it can know which row its responsible for GC.

Modify CRDB tables to have a "writer" column

---

build/README.md
build/deploy/db-schemas/scd.libsonnet
build/deploy/db-schemas/scd/000001_create_initial_version.up.sql
build/deploy/examples/minimum/main.jsonnet
build/deploy/grpc-backend.libsonnet
build/deploy/metadata_base.libsonnet
build/deploy/schema-manager.libsonnet
cmds/db-manager/main.go
cmds/grpc-backend/main.go
pkg/cockroach/cockroach.go
pkg/rid/store/cockroach/store.go
pkg/scd/store/cockroach/store.go
test/docker_e2e.sh

This PR moves SCD data into its own database (named "scd") and introduces migrations to that database.
One consequence of the approach here is that a single CRDB connection is no longer shared between RID & SCD.  We could share a single connection, but all the SQL statements would need to be rewritten to prefix table names with the correct database.  This probably seems worthwhile, but the RID database should be changed from "defaultdb" to "rid" before adding all those database name prefixes, and this is better-suited to a PR separate from this one.
The PR also pipes the enableScd grpc-backend option through deployment configurations.

Split SCD data into dedicated `scd` database

---

monitoring/get_access_token.py
monitoring/prober/Dockerfile
monitoring/prober/README.md
monitoring/prober/auth.py
monitoring/prober/aux/test_token_validation.py
monitoring/prober/conftest.py
monitoring/prober/infrastructure.py
monitoring/prober/requirements.txt
monitoring/prober/rid/test_isa_expiry.py
monitoring/prober/rid/test_isa_simple.py
monitoring/prober/rid/test_isa_validation.py
monitoring/prober/rid/test_subscription_isa_interactions.py
monitoring/prober/rid/test_subscription_simple.py
monitoring/prober/rid/test_subscription_validation.py
monitoring/prober/rid/test_token_validation.py
pkg/aux_/server.go
pkg/rid/server/server.go
test/docker_e2e.sh

This PR restructures the prober auth specification to be a single command line option for each token source (see changes in docker_e2e.sh for an example).  The format for the specification is reflected from AuthAdapter classes that implement various token retrieval techniques.
This is necessary because the PR also adds two new token retrieval methods (because the DSS is being used in two new settings) and having alternate parameters (in ad-hoc groups) for all methods would have been a big maintenance difficulty.  This PR also eliminates a substantial number of lines of code from the prober while improving the readability of auth option specification.
Prompted by testing with this PR, explicit scopes are added to the RID prober tests and #361 is fixed.

Restructure prober auth configuration

---

build/build.sh

We recently created a script to produce a standard git-informed version string.  This PR uses that script in build.sh for naming docker images.

Make image version names consistent

---

build/deploy/base.libsonnet
build/deploy/istio/base.libsonnet

Istio no support Mesh Policy in v1alpha1 and there doesn't seem to be a replacement so its removed.
DB Manager job was failing to complete due to a bug in K8s when there is a side car injected. We don't need sidecar for this job and the current suggested work around is to remove it until K8s implements a fix #372

Fix Istio deployment + Db-manager errors

---

build/deploy/db_schemas/defaultdb/000002_inverted_index.down.sql
build/deploy/db_schemas/defaultdb/000002_inverted_index.up.sql
build/deploy/db_schemas/defaultdb/000003_migrate_data_to_index.up.sql
build/deploy/db_schemas/defaultdb/000004_drop_cells_table.up.sql
build/deploy/db_schemas/defaultdb/000005_bump_version.down.sql
build/deploy/db_schemas/defaultdb/000005_bump_version.up.sql
build/deploy/db_schemas/defaultdb/000006_add_writer_column.down.sql
build/deploy/db_schemas/defaultdb/000006_add_writer_column.up.sql

Constraints name must be unique and applying the constraints to upgrade from old V2 where bootstrap scripts was in GRPC we needed to rename the constraints the make the run valid

Fix SQL statements

---

cmds/grpc-backend/main.go
pkg/auth/auth.go
pkg/rid/application/subscription_test.go
pkg/rid/models/identification_service_area.go
pkg/rid/server/isa_handler.go
pkg/rid/server/server.go
pkg/rid/server/server_test.go
pkg/scd/store/cockroach/subscriptions.go

#349 
1. Adding Locality field to rid.Server
2. Adding Writer field to ISA obj
3. Adding code to set Locality value to writer field when update ISA
4. Adding unit test for updating ISA
Next:
update update sql script in store.go for rid db that version >= v3.1.0

Set locality value to writer field in isa obj for update ISA

---

go.mod
go.sum
monitoring/prober/scd/test_operation_references_error_cases.py
pkg/errors/errors.go
pkg/models/models.go
pkg/rid/application/subscription.go
pkg/rid/server/isa_handler.go
pkg/rid/server/subscription_handler.go
pkg/rid/store/cockroach/identification_service_area.go
pkg/scd/constraints_handler.go
pkg/scd/models/constraints.go
pkg/scd/models/models.go
pkg/scd/models/operations.go
pkg/scd/models/subscriptions.go
pkg/scd/operations_handler.go
pkg/scd/repos/repos.go
pkg/scd/store/cockroach/constraints.go
pkg/scd/store/cockroach/operations.go
pkg/scd/store/cockroach/subscriptions.go
pkg/scd/subscriptions_handler.go

This PR begins to address #379 by:
1. Replacing all of our explicit Internal errors with `stacktrace` messages and propagations
1. Adding an error ID so a particular client-facing error message can be connected to backend logs quickly and easily, even if error message details are obfuscated
1. Fixing a number of issues with input validation and implicit Subscriptions exposed by the work above
In future PRs, we can add more `stacktrace.Propagate` statements to improve visibility into error causes, but that will be a large task and this PR aims to be a targeted introduction to the work.

Add detailed error message infrastructure

---

monitoring/prober/scd/test_operation_references_error_cases.py
monitoring/prober/scd/test_operation_simple_heavy_traffic.py
monitoring/prober/scd/test_operations_simple.py
pkg/scd/constraints_handler.go
pkg/scd/errors/errors.go
pkg/scd/models/models.go
pkg/scd/models/operations.go
pkg/scd/models/subscriptions.go
pkg/scd/operations_handler.go
pkg/scd/repos/repos.go
pkg/scd/server.go
pkg/scd/store/cockroach/operations.go
pkg/scd/store/cockroach/subscriptions.go
pkg/scd/subscriptions_handler.go
test/README.md

This PR primarily simplifies the internal store/repo interface for Operations per #277, and, in the process, incidentally fixes #344, #385, and #391, and partially addresses #386.  An additional adjustment regarding Operations is that DependentSubscriptions is removed from the Subscription model since it was not consistently populated -- instead, this information can be obtained via a separate repo call when needed.  A few tests are augmented, and the validity of end times in the past is clarified in a few cases (ok to query Operations in the past, not ok to create/update an Operation to have its end time in the past).

Simplify Operations repo interface and fix some Operation behavior

---

go.mod
go.sum
pkg/errors/errors_test.go

Fixes #417, #418, #419, #420, #421

[stacktrace] Switch to interuss fork

---

monitoring/prober/rid/test_isa_expiry.py
monitoring/prober/rid/test_isa_simple.py
monitoring/prober/rid/test_isa_validation.py
monitoring/prober/rid/test_subscription_isa_interactions.py
monitoring/prober/rid/test_subscription_simple.py
monitoring/prober/rid/test_subscription_validation.py
monitoring/prober/rid/test_token_validation.py
monitoring/prober/scd/test_operation_special_cases.py

The PR ensures that the prober prints the server response whenever an unexpected status code is received -- this enables more rapid and effective debugging when a prober test fails.

[prober] Always print response upon status code assertion failure

---

cmds/grpc-backend/main.go
go.mod
go.sum

We've seen that when CRDB dies or when the connection to it dies it doesn't get automatically reconnected. To fix this we ping the DB ever minute to refresh the connection.
cc: @Dos-Ph as an example for scheduling Garbage collector

Auto DB ping and reconnect

---

build/README.md
build/deploy/db_schemas/defaultdb/000007_add_index_by_time_subscriptions.down.sql
build/deploy/db_schemas/defaultdb/000007_add_index_by_time_subscriptions.up.sql
build/deploy/examples/minimum/main.jsonnet
build/deploy/examples/prod/main.jsonnet
build/deploy/examples/schema_manager/main.jsonnet
build/dev/startup/rid_bootstrapper.sh
pkg/rid/application/isa_test.go
test/docker_e2e.sh

Querying number of subscriptions is the bottle neck for inserting Subscriptions. Adding an index here making removes the full scan in the query. 
Ideally we want to index on cells however it is not supported in CRDB yet, They anticipate that v20.2 will support creating forward index on array

Add Index on end_at for improved performance

---

build/README.md

in CRDB v20 they remove the cli command for creating user, now we have to do it with sql commands

Update create user for crdb

---

monitoring/monitorlib/infrastructure.py

This small PR fixes a bug in the logic of refreshing tokens to avoid attempting calls with expired tokens.

[monitoring] Fix token refresh timing bug

---

build/deploy/prometheus_configs/istio.libsonnet

for prometheus to scrape cockroachdb we need to allow insecure_skip_verify set to true to skip verifying the cert matched the url its scraping. we already enable this in 'k8s-endpoint' job and don't need to double scrape in 'kubernetes-service-endpoint'

Fix 'remote error: tls: bad certificate'

---

Makefile
build/dev/docker-compose_dss.yaml
test/docker_e2e.sh

PR #469 upgraded CockroachDB usage to 20.2.0 in the production configuration, but did not change the references in the development and test tools to match.  This PR updates all CRDB usage in the repo, including the end-to-end test, Makefile test, and stand-along dev instance, to 20.2.0.

Update CRDB version to 20.2.0 in non-production usages

---

build/README.md
build/dev/check_dss.sh
build/make-certs.py

- We have a check to see if the user has _jq_ installed. But check logic does the opposite. The PR fixed the logic.
- We have a Python script written in Python 3. An error occurs when the default local version is Python 2. Specifying the Python version solves this problem. (Another solution would be to modify the script so that both versions work)
- Fixed some typos.

Update jq version checking logic and fixed some typos.

---

build/dev/startup/grpc_backend.sh
monitoring/monitorlib/auth.py
monitoring/monitorlib/infrastructure.py
monitoring/tracer/Dockerfile
monitoring/tracer/requirements.txt
monitoring/tracer/resources.py
monitoring/tracer/run_poll_locally.sh
monitoring/tracer/run_subscribe_locally.sh
monitoring/tracer/tracerlog.py
monitoring/tracer/uss_receiver/routes.py
monitoring/tracer/uss_receiver/templates/logs.html

This PR adds a `KML_SERVER` flag to the `tracer` tool which `tracer` will send new logs to in order to generate KMLs representing the state of the system.  Those KMLs are cached by `tracer` and then served to clients when requested.  If the new flag is not specified, `tracer` behaves as before.

Add ability for tracer to incorporate KMLs generated by external server

---

monitoring/interoperability/Dockerfile
monitoring/loadtest/Dockerfile
monitoring/monitorlib/geo.py
monitoring/monitorlib/rid.py
monitoring/monitorlib/typing.py
monitoring/prober/Dockerfile
monitoring/rid_qualifier/mock/Dockerfile
monitoring/rid_qualifier/mock/Postman_rid_qualifier_mock_test.json
monitoring/rid_qualifier/mock/README.md
monitoring/rid_qualifier/mock/__init__.py
monitoring/rid_qualifier/mock/api.py
monitoring/rid_qualifier/mock/clustering.py
monitoring/rid_qualifier/mock/database.py
monitoring/rid_qualifier/mock/debug_mock.py
monitoring/rid_qualifier/mock/requirements.txt
monitoring/rid_qualifier/mock/routes.py
monitoring/rid_qualifier/mock/run_locally.sh
monitoring/tracer/Dockerfile

This PR adds a tool that simulates an entire remote ID ecosystem for the purpose of testing rid_qualifier; see more information in [the README added in this PR](https://github.com/BenjaminPelletier/dss/blob/rid_qualifier/mock/monitoring/rid_qualifier/mock/README.md).  Simply having this tool running (with run_locally.sh) should enable full testing of rid_qualifier without the need for any other RID Service Providers, RID Display Providers, or a DSS.
A moderate amount of this PR is dedicated to adding `ImplicitDict` (in monitoring.monitorlib.typing), a base class that should make management of schema-defined objects easier, especially with regard to JSON serialization and deserialization.

Add mock RID system to test rid_qualifier

---

monitoring/monitorlib/README.md
monitoring/monitorlib/auth.py

This PR adds an AuthAdapter that allows the user to generate valid access tokens without referencing (or requiring) any server.  This can save the effort of setting up a Dummy OAuth server locally in certain debugging/development situations.

Add NoAuth AuthAdapter

---

monitoring/monitorlib/typing.py
monitoring/rid_qualifier/mock/routes.py

This PR improves rid_qualifier mock's responses when various types of invalid requests are submitted.  This includes an explicit error when attempting to parse dictionary data with ImplicitDict.parse and instead finding data of a different type (like a str or NoneType), and explicitly indicating that a JSON payload was not included when it is not present.

Increase ImplicitDict robustness and improve rid_qualifier mock responses

---

monitoring/rid_qualifier/aircraft_state_replayer.py
monitoring/rid_qualifier/flight_data_generator.py
monitoring/rid_qualifier/operator_flight_details_generator.py
monitoring/rid_qualifier/rid_qualifier_entry.py
monitoring/rid_qualifier/test_executor.py
monitoring/rid_qualifier/utils.py

This PR prepares for the introduction of display_data_evaluator by streamlining the data flow through the previous parts of rid_qualifier.  It substantially reduces the number of data types by using interface-specified types when practical.  For instance, all "payloads" are converted to injection-interface-specified `CreateTestParameters` or components thereof, and multiple details types are combined in a single `FlightDetails` which references RID-interface-specified `RIDFlightDetails`.  It also fixes the bug where all flights would be assigned the same operator.

rid_qualifier: Streamline data type flow through simulation and injection

---

monitoring/monitorlib/fetch/__init__.py
monitoring/monitorlib/requirements.txt
monitoring/monitorlib/rid.py
monitoring/monitorlib/typing.py
monitoring/rid_qualifier/.gitignore
monitoring/rid_qualifier/aircraft_state_replayer.py
monitoring/rid_qualifier/display_data_evaluator.py
monitoring/rid_qualifier/flight_data_generator.py
monitoring/rid_qualifier/injection_api.py
monitoring/rid_qualifier/observation_api.py
monitoring/rid_qualifier/reports.py
monitoring/rid_qualifier/requirements.txt
monitoring/rid_qualifier/rid_qualifier_entry.py
monitoring/rid_qualifier/run_locally.sh
monitoring/rid_qualifier/test_executor.py
monitoring/rid_qualifier/utils.py

This PR adds a first draft of the part of rid_qualifier that observes an RID system and evaluates whether the data observed is consistent with the injected flight data.  It is primarily located in `display_data_evaluator.py`, called from `test_executor.py`.  A simple JSON-formatted report is generated as defined in `reports.py` tracking what data was injected into the system, what observations were made, and what issues were discovered.
A few utilities are improved to support these efforts, and the delays and default durations in rid_qualifier are reduced to support quicker development iteration.

rid_qualifier: Add first draft of display data evaluator

---

monitoring/mock_ridsp/Dockerfile
monitoring/mock_ridsp/README.md
monitoring/mock_ridsp/__init__.py
monitoring/mock_ridsp/auth.py
monitoring/mock_ridsp/config.py
monitoring/mock_ridsp/mockuss.py
monitoring/mock_ridsp/requirements.txt
monitoring/mock_ridsp/routes.py
monitoring/mock_ridsp/routes_ridsp.py
monitoring/mock_ridsp/run_locally.sh
monitoring/monitorlib/auth_validation.py

This PR adds the start of a mock remote ID service provider.  While it currently only responds to endpoints with trivial hard-coded responses, the intent is to enhance it in later PRs to accept injected test data and properly report that data (including interacting with the DSS when appropriate).

[mock_ridsp] Add skeleton mock RID SP

---

monitoring/rid_qualifier/aircraft_state_replayer.py
monitoring/rid_qualifier/display_data_evaluator.py
monitoring/rid_qualifier/reports.py
monitoring/rid_qualifier/rid_qualifier_entry.py
monitoring/rid_qualifier/run_locally.sh
monitoring/rid_qualifier/test_executor.py
monitoring/rid_qualifier/utils.py

This PR enables rid_qualifier to accept a single JSON-based configuration description (`RIDQualifierTestConfiguration`) for its test(s), which fills in the gaps of allowing the user to specify various parameters that were previously hard-coded.
`run_locally.sh` is updated to demonstrate how this configuration is provided, and also includes a multi-injection-target, multi-observer test, and is also adjusted so that it no longer needs to be run from a specific working directory.
The `auth_spec` is kept separate from the configuration because it often contains sensitive data (e.g., passwords) that would be insecure to store along side other configuration data.

[rid_qualifier]Accept JSON configuration as input

---

monitoring/mock_ridsp/database.py
monitoring/mock_ridsp/resources.py
monitoring/mock_ridsp/routes_injection.py
monitoring/monitorlib/geo.py
monitoring/monitorlib/mutate/rid.py
monitoring/monitorlib/rid.py
monitoring/monitorlib/rid_automated_testing/injection_api.py

This PR improves mock_ridsp to insert an ISA into the DSS for each injected test, and then delete that ISA when the test is deleted.
After this PR is submitted, mock_ridsp should behave as a complete RID Service Provider, capable of interacting with a standard RID Display Provider.

[mock_ridsp] Implement ISA insertion into DSS

---

monitoring/monitorlib/README.md
monitoring/monitorlib/auth.py
monitoring/monitorlib/auth_utils.py

First commit for new Auth Adapter based on the open source Flight Passport project

Initial Commit / Adding Flight Passport OAUTH server to AuthSpec

---

monitoring/mock_ridsp/run_locally.sh

The RID SP exposes the injection api at /ridsp endpoint, fixing this in `run_locally.sh`

Fix the endpoint URL in run_locally.sh

---

cmds/dummy-oauth/main.go
go.mod
go.sum
pkg/auth/auth.go
pkg/auth/auth_test.go
pkg/auth/claims.go
pkg/rid/application/application.go
pkg/rid/application/application_test.go
pkg/rid/store/cockroach/garbage_collector_test.go
pkg/rid/store/cockroach/identification_service_area_test.go
pkg/rid/store/cockroach/store.go
pkg/rid/store/cockroach/store_test.go
pkg/rid/store/cockroach/subcriptions_v3.go
pkg/rid/store/cockroach/subscriptions.go
pkg/rid/store/cockroach/subscriptions_test.go
pkg/scd/store/cockroach/store.go
pkg/scd/subscriptions_handler.go

This PR primarily updates Go dependencies to replace github.com/dgrijalva/jwt-go with https://github.com/golang-jwt/jwt to address the security issue with the former dependency.
It also replaces DPJacques/clockwork with the root forked repository jonboulle/clockwork as the former incorrectly declares itself as the latter, and that problem seems to have been causing build problems.

[dependencies] Update Go dependencies

---

scripts/why_go_dep.py

Sometimes it is unclear why a Go package is included in a build, such as some of the packages mentioned in #473.  This PR adds a small script to visualize the connections between dependencies that lead to a package being included in a build.

[tools] Add script to show transitive Go dependencies

---

monitoring/mock_ridsp/routes_injection.py

mock_ridsp previously created an ISA that tightly wrapped the injected positions, but this was non-compliant with NET0610 which requires that the flight be encompassed in an ISA for 60 seconds after the end of the flight.  This PR buffers the end time of the ISA more than 60 seconds past the last position report to be compliant with NET0610.

[mock_ridsp] Fix ISA duration by adding trailing buffer

---

monitoring/rid_qualifier/run_flight_data_generator.sh

This PR adds a script to run flight_data_generator.py in the docker container. It allows a developer to generate the initial test dataset without installing the python dependencies on his local host.

Add script to run flight_data_generator of rid_qualifier in the docker container

---

monitoring/monitorlib/typing.py

When a type has a field defined as `Optional[SomeType]` and `None` is provided for that field, ImplicitDict interprets the user to be positively declaring the value of that field to be `None` (thus triggering an unsuccessful attempt to parse `None` as an instance of `SomeType`), which is different from omitting the field.  The better interpretation is that specifying `None` for an `Optional` field should be equivalent to omitting the field.  This PR implements that change.

[monitoring] Fix ImplicitDict parsing of optional fields containing explicit null

---

monitoring/monitorlib/scd.py
monitoring/prober/conftest.py
monitoring/prober/infrastructure.py
monitoring/prober/scd/test_operation_simple.py

To prepare for upgrading tests to support SCD DSS API version 0.3.15 (or later), this PR introduces a tool to annotate prober tests as supporting a particular set of API versions.

[prober] Add API-dependence tool for prober tests

---

build/dev/probe_local_instance.sh
go.mod
monitoring/prober/README.md
monitoring/prober/conftest.py
monitoring/prober/rid/common.py
monitoring/prober/rid/test_isa_simple.py
monitoring/prober/rid/test_subscription_simple.py
monitoring/prober/scd/test_constraint_simple.py
monitoring/prober/scd/test_constraints_with_subscriptions.py
monitoring/prober/scd/test_operation_references_error_cases.py
monitoring/prober/scd/test_operation_references_state_transition.py
monitoring/prober/scd/test_operation_simple.py
monitoring/prober/scd/test_operation_special_cases.py
monitoring/prober/scd/test_operations_simple.py
monitoring/prober/scd/test_subscription_queries.py
monitoring/prober/scd/test_subscription_query_time.py
monitoring/prober/scd/test_subscription_simple.py
monitoring/prober/scd/test_subscription_update_validation.py
monitoring/prober/utils.py
pkg/rid/server/isa_handler.go
pkg/rid/server/subscription_handler.go
test/docker_e2e.sh

This PR prepares for the effort of fixing tests on the [path to updated SCD API support](https://github.com/interuss/dss/wiki/Updating-SCD-API) by targeting automated tests to API version 0.3.15 and pulling #549 into the scd_api_update branch.
The only change in this PR beyond #549 is the addition of `--scd-api-version 0.3.15` in docker_e2e.sh.

[scd] Prep for test fixes

---

pkg/scd/models/models.go

This PR resolves issue #TBD where OVNs are used in URL paths as of 0.3.17 and so must be URL-safe.  This PR makes OVNs URL-safe by changing the URL-unfriendly base64 characters into URL-friendly ones.

[scd] Make OVNs URL-safe

---

Makefile
build/dev/probe_local_instance.sh
build/dev/run_locally.sh
build/dev/startup/grpc_backend.sh
build/dev/startup/rid_bootstrapper.sh
build/dev/startup/scd_bootstrapper.sh
monitoring/mock_riddp/run_locally.sh
monitoring/mock_ridsp/run_locally.sh
monitoring/rid_qualifier/host/run_locally.sh
monitoring/rid_qualifier/mock/run_locally.sh
monitoring/rid_qualifier/run_flight_data_generator.sh
monitoring/rid_qualifier/run_flight_state_locally.sh
monitoring/rid_qualifier/run_locally.sh
monitoring/rid_qualifier/test_fully_mocked_local_system.sh
monitoring/tracer/run_poll_locally.sh
monitoring/tracer/run_subscribe.sh
monitoring/tracer/run_subscribe_locally.sh

This pull request fixes shell scripts in order to pass shellcheck linter test.
Test command:
> make lint
Please note that there are few TODO comments to be discussed with reviewers.

Fix shell scripts to pass linter

---

monitoring/prober/scd/test_operation_references_error_cases.py
monitoring/prober/scd/test_operation_simple.py
pkg/scd/models/operational_intents.go
pkg/scd/store/cockroach/operational_intents.go

Depends on #570 (Shall be merged first). This PR is targetting scd_api_update for readability.
Fixes : 
- `scd/test_operation_simple.py::test_create_op_v15`
- `scd/test_operation_references_error_cases.py::test_missing_conflicted_operation_v15`
- `scd/test_operation_references_error_cases.py::test_op_repeated_requests_v15`

[scd] Fix #569: second part

---

build/deploy/db_schemas/scd/000002_support_api_1_0_0.up.sql
pkg/scd/models/subscriptions.go
pkg/scd/operational_intents_handler.go
pkg/scd/store/cockroach/subscriptions.go
pkg/scd/subscriptions_handler.go

Fixes #589 by treating the Subscription version as an OVN string populated from updated_at.  This makes the version column in the database unnecessary, but it is retained for now to support ease of database downgrading.

[scd] Change Subscription version to OVN

---

monitoring/prober/scd/test_operations_simple.py

This PR fixes the prober v17 tests of `scd/test_operations_simple.py`.
Test command: `test/docker_e2e.sh scd/test_operations_simple.py`

Fix scd/test_operations_simple (v17)

---

build/dev/startup/grpc_backend.sh
monitoring/prober/scd/test_constraints_with_subscriptions.py
monitoring/prober/scd/test_operation_simple_heavy_traffic.py

In the process of updating prober tests to support the 0.3.17 SCD API, a few 0.3.5 tests were accidentally broken.  This PR fixes those 0.3.5 tests.

[prober] Fix tests for SCD 0.3.5 API

---

monitoring/monitorlib/requirements.txt
monitoring/prober/requirements.txt

aiohttp is required in /monitoring/monitoringlib/infrastructure.py

Fix aiohttp dependency location

---

CONTRIBUTING.md
DEVELOPMENT.md

This PR proposes Contributing guidelines based on the experience of the previous months working with @BenjaminPelletier .
It includes a first attempt to set development guidelines and kick start an harmonization effort of the projects in the repository.

Contribution guidelines

---

interfaces/automated-testing/scd/scd.yaml

This is the first PR of series which will fully specify the SCD testing interfaces. 
The payloads for the requests, have been left out for the next PRs.

Initial Specification of /inject/flight endpoint for SCD automated tests

---

interfaces/automated-testing/scd/scd.yaml

This PR adds the operational_intent_id field to the InjectFlightResponse object in order to facilitate tracking of the test flight submitted by the test driver. For instance, querying the DSS or the USS under test Operational Intent details endpoint.
As per the OpenAPI specification, [a reference object cannot be extended with additional properties and any properties added SHALL be ignored.](https://swagger.io/specification/#reference-object). Following the model of the [UTM OpenAPI spec](https://github.com/astm-utm/Protocol/blob/master/utm.yaml#L135), this PR either uses anyOf wrapper to preserve the description or removes redundant descriptions.

[automated/scd] Add operational_intent_id to InjectFlightResponse

---

monitoring/mock_riddp/__init__.py
monitoring/mock_riddp/routes_observation.py
monitoring/mock_ridsp/__init__.py
monitoring/mock_ridsp/run_locally.sh
monitoring/uss_qualifier/.gitignore
monitoring/uss_qualifier/README.md
monitoring/uss_qualifier/bin/generate_rid_test_definition.sh
monitoring/uss_qualifier/main.py
monitoring/uss_qualifier/rid/.gitignore
monitoring/uss_qualifier/rid/aircraft_state_replayer.py
monitoring/uss_qualifier/rid/simulator/flight_state.py
monitoring/uss_qualifier/rid/test_executor.py
monitoring/uss_qualifier/run_locally.sh
monitoring/uss_qualifier/test_fully_mocked_local_system.sh
monitoring/uss_qualifier/webapp/tasks.py
monitoring/uss_qualifier/webapp/templates/base.html

This PR moves the main entrypoint for automated testing from the `rid` folder to the main `uss_qualifier` folder.  The tests performed and listed below revealed some issues and possible improvements which are also addressed in this PR.
After deleting test_definitions:
1. `monitoring/uss_qualifier/rid/mock/run_locally.sh`
2. `monitoring/uss_qualifier/run_locally.sh`
1. `build/dev/run_locally.sh`
2. `monitoring/mock_ridsp/run_locally.sh`
3. `monitoring/mock_riddp/run_locally.sh`
4. `monitoring/uss_qualifier/test_fully_mocked_local_system.sh`
1. `monitoring/uss_qualifier/bin/generate_rid_test_definitions.sh`
...then rerun Full system mock
1. `build/dev/run_locally.sh`
2. `monitoring/mock_ridsp/run_locally.sh`
3. `monitoring/mock_riddp/run_locally.sh`
4. …

[automated-testing] Migrate old rid_qualifier entrypoint to uss_qualifier

---

monitoring/uss_qualifier/main.py
monitoring/uss_qualifier/rid/test_executor.py
monitoring/uss_qualifier/rid/utils.py
monitoring/uss_qualifier/run_locally.sh
monitoring/uss_qualifier/scd/test_executor.py
monitoring/uss_qualifier/scd/utils.py
monitoring/uss_qualifier/utils.py

This PR adds a placeholder for SCD automated tests execution and proposes an update of the configuration schema to handle multiple services.
It assumes the locale will be the same for all services under test.

[uss_qualifier] Add SCD entrypoint and update config schema

---

pkg/version/version.go

Arguments of the [Sscanf](https://pkg.go.dev/fmt#Sscanf) were inverted not parsing correctly the version tag.

[version] Fix version parsing

---

cmds/grpc-backend/main.go
pkg/cockroach/cockroach.go

Currently, there is a private `connectTo` method in the grpc-backend that produces a CockroachDB connection, but hides the fact that the the connection parameters for that connection come from flags defined in an entirely different package.  This PR changes the `ConnectTo` method to accept only the full, explicit parameter set, makes the method public in the main `cockroach` package to prepare for reuse in other areas, and makes the origin of the rest of the connection parameters more clear in the grpc-backend.

[crdb] Extract connectTo method to prepare for reuse

---

monitoring/uss_qualifier/scd/data_interfaces.py

Following up on #669, this PR adjusts formatting to follow [PEP 257](https://www.python.org/dev/peps/pep-0257/) and adjusts documentation descriptions per [this comment](https://github.com/interuss/dss/pull/669#pullrequestreview-858520616).

[uss_qualifier/scd] Adjust comments and formatting on interface between test executor and simulator

---

scripts/tag.sh

This PR updates the tag script to use the `origin` remote.

[scripts/release] Change remote branch used for tags to origin

---

cmds/dummy-oauth/README.md
cmds/dummy-oauth/main.go
interfaces/dummy-oauth/dummy-oauth.yaml

We currently have a webserver in cmds/dummy-oauth that generates DSS-consumable access tokens for development purposes.  Its API is currently implicit in the Go code implementing the handler.  This PR makes the API explicit and also adds a README explaining the tool and intended usage.  Not only will this make the tool more usable and approachable by new users, but it also prepares for using the new interfaces/openapi-to-go-server tool to autogenerate the webserver part of Dummy OAuth.

[dummy-oauth] Add API definition for Dummy OAuth

---

Makefile
interfaces/openapi-to-go-server/rendering.py

This PR adds a few small updates to openapi-to-go-server.  The primary one is better support for float query parameters (and some improvement in int support as well).  Also, support is added for responses with empty bodies.  Finally, the `make apis` target is extended to also regenerate the example API code.

[openapi-to-go-server] Improve float query parameter support

---

cmds/core-service/main.go

This PR fixes #691 in the near-mid term.  Long term, we will want to check our database client's behavior.

[core-service] Do not panic when TotalConns==0

---

cmds/core-service/README.md
cmds/core-service/main.go
cmds/http-gateway/README.md
cmds/http-gateway/main.go
pkg/cockroach/cockroach.go
pkg/rid/application/application_test.go
pkg/rid/server/server.go
pkg/rid/store/cockroach/store.go
pkg/rid/store/cockroach/store_test.go

Currently, core-service will fail (panic) if it cannot connect to the specified CRDB instance or if that instance has not been bootstrapped (initialized) by db-manager.  This makes the bring-up of a system more difficult because all services are generally started at the same time, and the order in which they become available is unpredictable.  There is a band aid for this problem in the tools for a standalone instance: explicit signaling between containers via a shared volume + explicit startup delays.  However, 1) this is not ideal and 2) this does not exist for production deployments, so the first thing a deployer sees is multiple container failures with fatal error messages.  A similar problem exists for http-gateway when it cannot connect to its core-service instance.
This PR …

[core-service,http-gateway] Retry recoverable errors during core-service and http-gateway startups

---

interfaces/automated-testing/scd/scd.yaml
monitoring/mock_uss/config.py
monitoring/mock_uss/mockuss.py
monitoring/mock_uss/postman_collection.json
monitoring/mock_uss/scdsc/database.py
monitoring/mock_uss/scdsc/routes.py
monitoring/mock_uss/scdsc/routes_injection.py
monitoring/mock_uss/scdsc/routes_scdsc.py
monitoring/monitorlib/clients/scd.py
monitoring/monitorlib/scd.py
monitoring/monitorlib/scd_automated_testing/scd_injection_api.py

This PR finishes a basic mock strategic coordination SCD USS, minus validation of flight authorisation information.
First, the SCD flight injection API is updated to include a `notes` field to eventually inform the reader of the report generated by uss_qualifier why the USS behaved the way it did (e.g., why a flight injection attempt Failed).
The mock USS now also performs its subscriber notification duties following creation of an operational intent.
Because this mock implementation is naive, it will query itself for details of its own operations (currently -- this could be improved in the future).  This means that the handler for flight injection will call the handler for flight details, which means the mock USS webserver must have at least 2 workers (this was changed in the previous …

[uss_qualifier/scd] Complete MVP for mock_uss's scdsc module

---

monitoring/mock_uss/config.py
monitoring/monitorlib/locality.py
monitoring/uss_qualifier/main.py
monitoring/uss_qualifier/scd/test_executor.py

This PR adds to the USS qualifier the ability to load automated tests files generated in #685.
`BehaviorLocality` defined in uss_mock config was moved to monitoringlib to leverage locality definition in the uss_qualifier simulator and test-executor.

[uss_qualifier/scd] Load automated tests files

---

interfaces/automated-testing/scd/scd.yaml
monitoring/mock_uss/scdsc/routes_injection.py
monitoring/monitorlib/clients/scd.py
monitoring/monitorlib/scd_automated_testing/scd_injection_api.py
monitoring/uss_qualifier/scd/data_interfaces.py

Currently, there is no way to instruct a USS to delete a flight created for an automated test.  This means that the system cannot be effectively cleared following the completion of a test.  This PR fixes that problem by adding a "delete flight" operation in the SCD automated testing API.
This PR also adjusts the definition of an AutomatedTest to specify generic "test steps" (rather than requiring every step to be a flight injection attempt) and includes the deletion of a flight as an action that can be defined within an automated test.  This would be useful to, e.g., check the caching behavior of a USS by injecting flight 1 into USS1, injecting flight 2 which is nearby but not conflicting into USS2, deleting flight 1 from USS1, then injecting flight 3 which conflicts with now-absent …

[uss_qualifier/scd] Add flight deletion capability to SCD automated testing

---

monitoring/validate_access_token.py

We already have a tool to exercise the monitoring auth framework to retrieve a token, but it was not previously easy to verify the validity of that token without potentially exposing the token using a site like jwt.io.  This PR adds a simple script to check a token's validity locally.

[monitoring] Add tool to validate access tokens

---

Makefile
build/dev/check_scd_clear.sh
build/dev/check_scd_read.sh
build/dev/check_scd_write.sh
build/dev/read_scd_constraint_reference.sh
build/dev/read_scd_operational_intent_reference.sh
build/dev/read_scd_subscription.sh
build/dev/standalone_instance.md
monitoring/prober/infrastructure.py

#696 added tools to inject data into an SCD database for the purpose of verifying database down migration behavior.  This PR simplifies the usage of those tools and generalizes them for potential other purposes as well.  It also documents the tools' purpose and usage in the README.
This PR also splits out the two types of lint (Go and shell) so that the shell lint (much quicker) can be run independently from the Go lint.

[dev tools] Expand and document local SCD data injection tools

---

monitoring/monitorlib/requirements.txt
monitoring/uss_qualifier/rid/mock/requirements.txt

Since February 17, 2022, itsdangerous requirement is matching version 2.1.0 which is not supported by flask 1.1.2.
Stack trace of the issue:
```
Traceback (most recent call last):
File "/usr/local/bin/gunicorn", line 8, in <module>
sys.exit(run())
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 228, in run
super().run()
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
Arbiter(self).run()
File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 58, in __init__
self.setup(app)
File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 118, in setup …
```

[monitoring] Enforce itsdangerous package version to 2.0.1

---

monitoring/uss_qualifier/scripts/test_docker.sh

This PR improves the script used to test the scd qualifier by forcing the images of the mocks to be built without cache and it prints the container logs in case of starting failure.
Note: USS Qualifier Tests check is failing because of the issue addressed by PR #716.

[ci] Clear image cache and print logs in case of failure

---

README.md
monitoring/uss_qualifier/README.md
monitoring/uss_qualifier/bin/build.sh
monitoring/uss_qualifier/bin/run.sh
monitoring/uss_qualifier/config_run.json.dist
monitoring/uss_qualifier/run_locally_scd.sh
monitoring/uss_qualifier/scd/README.md

This PR adds instructions and helper scripts to run configurable automated tests locally  from a service provider point of view. Additionally it changes the module version to uss_qualifier instead of uss_qualifier_scd.

[uss_qualifier/scd] Local instructions

---

scripts/git/version.sh

We identified that if a module was never released, the version generated defaults to v0.0.0. To make itmeaningful, this PR adds the commit hash to the fallback version name. That will generate useful version name for unreleased projects such as the `uss_qualifier`.

[version] Append commit hash to default version 0.0.0

---

monitoring/uss_qualifier/scd/executor/executor.py

Currently, tests are skipped without warning when there are less configured targets than the required uss_roles in the test_definition. This PR adds a check and fail the execution if this case occurs.

[uss_qualifier/scd] Prevent test run with less configured targets than required uss_roles

---

monitoring/interoperability/README.md
monitoring/interoperability/interop_test_suite.py

Currently the interoperability script generates 403s during cleanup on the DSS under test. The DSS `/subscriptions` endpoint requires the scope `dss.write.identification_service_areas` to properly delete a suscription. This PR fixes that as well as an inexact command line example in the documentation.

[interop] Fix scope to delete subscription during Cleanup

---

monitoring/mock_uss/routes.py
monitoring/mock_uss/scdsc/routes_injection.py
monitoring/monitorlib/fetch/scd.py
monitoring/uss_qualifier/rid/utils.py
monitoring/uss_qualifier/run_locally_scd.sh
monitoring/uss_qualifier/scd/configuration.py
monitoring/uss_qualifier/scd/executor/executor.py
monitoring/uss_qualifier/scd/executor/report_recorder.py
monitoring/uss_qualifier/scd/executor/runner.py
monitoring/uss_qualifier/scd/executor/target.py
monitoring/uss_qualifier/scd/executor/test_steps/delete_flight.py
monitoring/uss_qualifier/scd/executor/test_steps/inject_flight.py
monitoring/uss_qualifier/scd/reports.py

This PR has uss_qualifier double check with the DSS and USS (acting as a USS itself) that the operational intent a USS reported injecting actually appears properly in the UTM system whenever a USS properly indicates Planned as their response to a flight injection attempt.
As a consequence of debugging some behaviors observed during development of this change, this PR also adds some improved error messages and mock USS behaviors and fixes a problem where issues discovered through TestRunnerErrors were not added to the report.

[uss_qualifier/scd] Check for injected operational intents in UTM system

---

monitoring/monitorlib/infrastructure.py
monitoring/prober/conftest.py
monitoring/prober/scd/actions.py
monitoring/prober/scd/test_constraint_simple.py
monitoring/prober/scd/test_constraints_with_subscriptions.py
monitoring/prober/scd/test_operation_references_error_cases_v0_3_17.py
monitoring/prober/scd/test_operation_references_error_cases_v0_3_5.py
monitoring/prober/scd/test_operation_references_state_transition.py
monitoring/prober/scd/test_operation_simple_heavy_traffic.py
monitoring/prober/scd/test_operation_simple_heavy_traffic_concurrent.py
monitoring/prober/scd/test_operation_simple_v0_3_17.py
monitoring/prober/scd/test_operation_simple_v0_3_5.py
monitoring/prober/scd/test_operation_special_cases.py
monitoring/prober/scd/test_operations_simple.py
monitoring/prober/scd/test_subscription_queries.py
monitoring/prober/scd/test_subscription_simple.py
monitoring/prober/scd/test_subscription_update_validation.py

Prior to this PR, cleaning of the workspace (deleting any previous instances of resources to be manipulated in the test) was unnecessarily verbose (same logic copy/pasted in many different files) and sometimes incorrect (API-dependence not respected in test_constraint_simple).  This PR creates a few generic actions in actions.py that are sensitive to API, and then calls them from all workspace cleaning pre-tests.  This fixes a 405 (method not supported) error when running test_constraint_simple on live instances under dirty conditions.

[prober] Fix, simplify, and improve workspace cleaning actions

---

go.mod
go.sum
pkg/cockroach/cockroach.go
pkg/cockroach/flags/flags.go
pkg/rid/store/cockroach/store.go
pkg/scd/store/cockroach/store.go

This PR upgrades github.com/cockroachdb/cockroach-go/v2 dependency to v2.2.8 in order to leverage better logging when a query fails after too many retry attempts.

[dss/crdb] upgrade github.com/cockroachdb/cockroach-go/v2 to v2.2.8

---

Makefile
build/deploy/metadata_base.libsonnet
build/dev/docker-compose_dss.yaml
cmds/core-service/README.md
test/docker_e2e.sh
test/migrations/clear_db.sh

This PR brings the cockroachdb image used in this repository to the latest version (v21.2.7)

[crdb] Upgrade cockroachdb to v21.2.7

---

monitoring/uss_qualifier/config_run.json.dist

Fix config example to include dss_base_url introduced in #731

[uss_qualifier] Add dss_base_url to config example

---

monitoring/prober/scd/test_operation_simple_heavy_traffic_concurrent.py

This PR addresses the short-term needs of #742.

[prober/scd] Align concurrency test acceptance criteria with short-term product needs

---

monitoring/uss_qualifier/bin/build.sh

This PR fixes the version in the build script. This was not noticed in #737 .

[uss_qualifier] Fix version in build script

---

monitoring/monitorlib/requirements.txt

This PR fixes #753 by forcing version of Werkzeug dependency to 2.0.3.

[uss_qualifier] Force version Werkzeug==2.0.3

---

monitoring/uss_qualifier/scd/test_definitions/CHE/astm-strategic-coordination/nominal-planning-1.json
monitoring/uss_qualifier/scd/test_definitions/CHE/astm-strategic-coordination/nominal-planning-priority-1.json
monitoring/uss_qualifier/scd/test_definitions/CHE/u-space/flight-authorisation-validation-1.json

Moved `uss_capabilities` out of test_steps, per the definition in https://github.com/interuss/dss/blob/master/monitoring/uss_qualifier/scd/data_interfaces.py#L89 
I found this issue while updating the simulator PR.

[uss_qualifier/scd] Test Definition: Fix structure of default data

---

build/deploy/cockroachdb-auxiliary.libsonnet

See https://github.com/kubernetes/kubernetes/issues/63741: the annotation `service.alpha.kubernetes.io/tolerate-unready-endpoints` has been replaced by the Service spec argument `publishNotReadyAddresses`.  This PR adds the new spec argument.  This is important because CRDB nodes must be able to communicate before they are ready in order to become ready.

[deployment] Add publishNotReadyAddresses to replace tolerate-unready-endpoints

---

monitoring/deployment_manager/actions/dss/v1/common.py
monitoring/deployment_manager/actions/dss/v1/crdb.py
monitoring/deployment_manager/deploylib/comparisons.py
monitoring/deployment_manager/deploylib/crdb_cluster_api.py
monitoring/deployment_manager/deploylib/crdb_sql.py
monitoring/deployment_manager/deploylib/port_forwarding.py
monitoring/deployment_manager/deploylib/secrets.py
monitoring/deployment_manager/deployment_manager.py
monitoring/deployment_manager/requirements.txt

This PR demonstrates interactions with a CockroachDB node's [cluster API](https://www.cockroachlabs.com/docs/api/cluster/v2) using a standard `requests.Session` via an underlying socket supplied by the `kubernetes` package that forwards to a port on the CockroachDB node's pod.
To use the action introduced in this PR:
1. Have a [standard DSS deployment](https://github.com/interuss/dss/tree/master/build) (deployed via Tanka using Kubernetes)
2. Create a `sites` folder within monitoring/deployment_manager
3. Add a deployment description in that `sites` folder pointing to the live DSS deployment; something like:
```json
{
"cluster": {
"name": "gke_your-cloud-project_your-region_your-cluster-name"
},
"dss": {
"v1": {
"namespace": "default"
}
}
}
```
4. You may need to have that context already …

[deployment_manager] Add CRDB cluster info via port-forwarded cluster API

---

monitoring/uss_qualifier/rid/test_executor.py

This PR fixes the output path of the report while running the `rid_qualifier` part of the toolset.

[uss_qualifier/rid]: Fix path and file name of report json in test executor

---

build/deploy/metadata_base.libsonnet
build/deploy/prometheus.libsonnet

Setting a custom Prometheus image is useful for:
- Providing a drop-in modified image for exporting metrics, e.g. [Google Cloud Managed Service for Prometheus](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-unmanaged).
- Setting a specific version to include bug fixes etc.
Additionally, the default Prometheus image was previously not pinned to a specific tag. This harms reproducibility, as the latest tag will be used at Pod startup. This PR addresses this by pinning the default image to the [latest version tag](https://hub.docker.com/r/prom/prometheus/tags) (`v2.35.0`). This improves reproducibility but does not completely guarantee it, as Docker Hub tags are mutable. Tagging to a digest would guarantee this, but this can be a topic for future discussion.

[deployment] Add the ability to specify a custom Prometheus image

---

monitoring/mock_uss/postman_collection.json
monitoring/mock_uss/riddp/behavior.py
monitoring/mock_uss/riddp/clustering.py
monitoring/mock_uss/riddp/database.py
monitoring/mock_uss/riddp/routes.py
monitoring/mock_uss/riddp/routes_behavior.py
monitoring/mock_uss/riddp/routes_observation.py
monitoring/mock_uss/ridsp/behavior.py
monitoring/mock_uss/ridsp/database.py
monitoring/mock_uss/ridsp/routes.py
monitoring/mock_uss/ridsp/routes_behavior.py
monitoring/mock_uss/ridsp/routes_ridsp.py
monitoring/monitorlib/fetch/rid.py
monitoring/monitorlib/typing.py
monitoring/uss_qualifier/README.md

Currently, there are two forms of mock systems for testing the RID portion of uss_qualifier:
* mock_uss, which behaves similarly to a real USS including use of a DSS
* The uss_qualifier RID mock, which does not require a DSS
An important characteristic the RID portion of uss_qualifier currently lacks is the ability to determine which USS is likely the cause of an interoperability problem.  The reason that this is the case currently is that the RID portion of uss_qualifier relies solely on the injection and observation interfaces, and so only observes that an injected flight does not reach the observation interface -- it cannot determine whether the problem between the injection and observation was due to the Service Provider or the Display Provider.  If uss_qualifier first probed a …

[mock_uss] Add RID misbehaviors to mock_uss

---

build/deploy/metadata_base.libsonnet
build/deploy/prometheus.libsonnet

Prometheus [recording rules](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/) provide a way to  create new time series which contain the results of a query. By providing the ability to add rules from within the Jsonnet config, consumers can easily create custom queries in PromQL, which can then be queried from other tools (e.g. Google Cloud Monitoring for alerting on these queries crossing thresholds).

[deployment] Add the ability to specify custom Prometheus recording rules

---

build/deploy/base.libsonnet
build/deploy/http-gateway.libsonnet

With Kubernetes v1.22, some (deprecated) `v1beta1` resources we relied on were removed entirely, with the expectation to upgrade to `v1`. These were:
- [`Ingress`, with some minor changes to the config structure.](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122)
- [`RBAC` resources, with no changes other than the version bump.](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#rbac-resources-v122)

[deployment] Update removed v1beta1 resource types to v1.

---

interfaces/automated-testing/geo-awareness/geo-awareness.yaml

This PR replaces the expected scope for the test driver in the Geo-Awareness automated testing interface definition to `geo-awareness.test`.

[interfaces] Update security scope to fit geo-awareness use case

---

monitoring/uss_qualifier/rid/aircraft_state_replayer.py
monitoring/uss_qualifier/rid/test_executor.py

Currently, the `rid` module of `uss_qualifier` discards the response from the test injection rather than using the flights (as injected) in the response.  This PR fixes that issue.

[uss_qualifier/rid] Use injected flights from test response rather than from request

---

monitoring/monitorlib/rid_common.py
monitoring/monitorlib/rid_v2.py
monitoring/uss_qualifier/rid/display_data_evaluator.py
monitoring/uss_qualifier/rid/test_executor.py
monitoring/uss_qualifier/rid/utils.py
monitoring/uss_qualifier/run_locally_rid.sh

Currently, the `rid` module of `uss_qualifier` only tests RID according to F3411-19 and not the latest published version F3411-22a.  This PR extends uss_qualifier to test according to either version of the standard.

[uss_qualifier/rid] Add RID version selector to uss_qualifier rid module

---

interfaces/automated-testing/geo-awareness/design/sequence.plantuml
interfaces/automated-testing/geo-awareness/geo-awareness.yaml

This PR adds to the Geo-Awareness automated testing interfaces the observation endpoint. The interface is defined to be as close as possible to the ED-269 interfaces.

[interfaces] Geo-Awareness: Observation API

---

interfaces/automated-testing/geo-awareness/geo-awareness.yaml

This PR makes some changes to the geo-awareness test API to:
1. Make it more broadly applicable to geo-awareness in non-U-space/ED-269 contexts
2. Clarify/unify some concepts (especially "selection of Geozones based on filter criteria")
3. Harmonize terminology between "UAS Zone" and "Geozone" (selecting "Geozone" as the more generic term)
4. Remove `/v1` prefixes
5. Make a few other smaller adjustments.

[uss_qualifier/geo-awareness] Update and generalize geo-awareness test API

---

build/README.md

Without the indentation, github's markdown reader looks a bit broken.

[docs] small formatting fix

---

monitoring/uss_qualifier/README.md
monitoring/uss_qualifier/main.py
monitoring/uss_qualifier/resources/README.md
monitoring/uss_qualifier/resources/__init__.py
monitoring/uss_qualifier/resources/communications/__init__.py
monitoring/uss_qualifier/resources/communications/auth_adapter.py
monitoring/uss_qualifier/resources/netrid/__init__.py
monitoring/uss_qualifier/resources/netrid/service_providers.py
monitoring/uss_qualifier/resources/resource.py
monitoring/uss_qualifier/rid/aircraft_state_replayer.py
monitoring/uss_qualifier/rid/test_executor.py
monitoring/uss_qualifier/rid/utils.py
monitoring/uss_qualifier/run_locally_rid.sh
monitoring/uss_qualifier/run_locally_scd.sh
monitoring/uss_qualifier/scd/configuration.py
monitoring/uss_qualifier/scd/data_interfaces.py
monitoring/uss_qualifier/scd/executor/executor.py
monitoring/uss_qualifier/scd/executor/target.py
monitoring/uss_qualifier/scd/executor/test_executor.py
monitoring/uss_qualifier/utils.py

This PR establishes an implementation framework for test resources (along with documentation in uss_qualifier/resources/README.md) and moves RID's "injection targets" from the "RID configuration" into this resources framework.  Future PRs will move all or nearly all of the RID configuration data structure into resource specifications in a similar way.

[uss_qualifier] Implement resources, move RID injection targets to resources

---

interfaces/automated-testing/geo-awareness/geo-awareness.yaml

This PR also improves on the GeozonesCheckResult (previously a simple boolean) by adding `UnsupportedFilter` and `Error` cases as well so that a USSP could return more granular and structured results rather than resorting to returning a 400 for the entire call.
Note: this PR previously made an additional change which is now *not* part of the PR.  That change was:
> This PR adds a filter to the geo-awareness automated testing API necessary to test geo-awareness capabilities in Australia where certain flight planning outcomes are expected on the basis of geo-awareness data.

[uss_qualifier/geo-awareness] Improve /check response in geo-awareness API

---

monitoring/uss_qualifier/main.py
monitoring/uss_qualifier/resources/netrid/__init__.py
monitoring/uss_qualifier/resources/netrid/evaluation.py
monitoring/uss_qualifier/resources/netrid/observers.py
monitoring/uss_qualifier/rid/display_data_evaluator.py
monitoring/uss_qualifier/rid/test_executor.py
monitoring/uss_qualifier/rid/utils.py
monitoring/uss_qualifier/run_locally_rid.sh

This PR follows #825 by moving RID observers and observation evaluation configuration into resource objects as well.

[uss_qualifier/rid] Move RID observers and evaluation configuration to resources

---

monitoring/monitorlib/inspection.py
monitoring/uss_qualifier/Makefile
monitoring/uss_qualifier/README.md
monitoring/uss_qualifier/requirements.txt
monitoring/uss_qualifier/scenarios/README.md
monitoring/uss_qualifier/scenarios/__init__.py
monitoring/uss_qualifier/scenarios/astm/netrid/nominal_behavior.md
monitoring/uss_qualifier/scenarios/astm/netrid/nominal_behavior.py
monitoring/uss_qualifier/scenarios/documentation/__init__.py
monitoring/uss_qualifier/scenarios/documentation/validate_documentation.py
monitoring/uss_qualifier/scenarios/documentation/validation.py
monitoring/uss_qualifier/scenarios/scenario.py
monitoring/uss_qualifier/scripts/in_container/validate_test_definitions.sh
monitoring/uss_qualifier/scripts/validate_test_definitions.sh

This PR adds documentation for the ASTM NetRID nominal behavior test scenario.  In addition, it adds programmatic documentation validation as a presubmit check to make sure all scenarios are fully documented, and it adds runtime availability of certain documentation information (especially requirements violated by failed test checks).  This is documented in uss_qualifier/scenarios/README.md.  Finally, this PR starts to transition TestScenario from a pure abstract class to more of a base class with some shared functionality (relating to reports) to be added in later PRs.

[uss_qualifier] Add strict scenario documentation

---

interfaces/automated-testing/geo-awareness/design/CHE/geo-awareness-che-1.json

While working on the mock_uss implementation of the geo-awareness service, some inaccuracies in the `interfaces/automated-testing/geo-awareness/design/CHE/geo-awareness-che-1.json` dataset appeared. This PR addresses them by removing empty fields and fix end of line markers to match the repository practice.
Note: Configure the diff to `Hide whitespace` to see the changes of interest.

[geo-awareness] Adapt CHE dataset to comply with ED269

---

monitoring/uss_qualifier/reports/report.py
monitoring/uss_qualifier/resources/netrid/service_providers.py
monitoring/uss_qualifier/scenarios/README.md
monitoring/uss_qualifier/scenarios/astm/netrid/injection.py
monitoring/uss_qualifier/scenarios/astm/netrid/nominal_behavior.md
monitoring/uss_qualifier/scenarios/astm/netrid/nominal_behavior.py
monitoring/uss_qualifier/scenarios/documentation/__init__.py
monitoring/uss_qualifier/scenarios/scenario.py
monitoring/uss_qualifier/suites/suite.py

Many test scenarios will want to attempt to clean up resources, both at the end of successful execution and when there is an aborting failure earlier.  This PR formalizes that mechanism by adding an optional special test step to test scenarios.  The state machine logic was less than obvious in TestScenario, so this PR also adds explicit state machine states ("phases") to hopefully make expectations and behavior a lot more clear in TestScenario.
A cleanup phase is also added to the NetRID nominal behavior test where the injected tests are deleted.

[uss_qualifier] Add optional cleanup phase to TestScenario

---

monitoring/mock_uss/Makefile
monitoring/mock_uss/__init__.py
monitoring/mock_uss/config.py
monitoring/mock_uss/geoawareness/database.py
monitoring/mock_uss/geoawareness/geozone_sources.py
monitoring/mock_uss/geoawareness/parsers/ed269/__init__.py
monitoring/mock_uss/geoawareness/parsers/ed269/ed269_test.py
monitoring/mock_uss/geoawareness/parsers/ed269/ed269_test_sample_dataset.json
monitoring/mock_uss/geoawareness/routes.py
monitoring/mock_uss/geoawareness/routes_geoawareness.py
monitoring/mock_uss/geoawareness/routes_geoawareness_test.py
monitoring/mock_uss/riddp/__init__.py
monitoring/mock_uss/ridsp/__init__.py
monitoring/mock_uss/run_locally_geoawareness.sh
monitoring/mock_uss/scdsc/__init__.py
monitoring/mock_uss/test.sh
monitoring/monitorlib/geoawareness_automated_testing/api.py
monitoring/monitorlib/requirements.txt

This PR adds an initial version of the geo-awareness mock_uss. It implements the /status and /geozone_source endpoints of the [geo-awareness automated testing interface](https://github.com/interuss/dss/blob/master/interfaces/automated-testing/geo-awareness/geo-awareness.yaml).
The geozone_source endpoint loads and parses ED269 formatted files and stores it "as is" in the in-memory database. This may be improved in a next PR addressing the checks endpoint.
To accomodate Common Information services, AUTH_SPEC and DSS_URL are now only required for collaborative services (RID and SCD).

[geo-awareness] [mock_uss] Initial Geo-Awareness Mock USS - Status and Geozone Source endpoint

---

build/apply-certs.sh

I guess the intention is that the default namespace should also contain the `cockroach.client.root` secret? If the namespace is not explicitly defined the secret will end up in whatever the user is currently using as current context namespace.

[cockroachdb][certs] explicitly set default namespace in apply-certs.sh

---

monitoring/uss_qualifier/resources/netrid/flight_data.py
monitoring/uss_qualifier/resources/netrid/flight_data_resources.py
monitoring/uss_qualifier/resources/netrid/simulation/adjacent_circular_flights_simulator.py
monitoring/uss_qualifier/resources/netrid/simulation/kml_flights.py
monitoring/uss_qualifier/resources/netrid/simulation/operator_flight_details.py
monitoring/uss_qualifier/test_data/che/netrid/circular_flights.json
monitoring/uss_qualifier/test_data/usa/netrid/dcdemo_flights.json

Currently, whenever RID simulation is run (including when the entire suite of local tests is run), different file content is generated for the two simulation outputs (circular_flights.json and dcdemo_flights.json).  This PR introduces configurable stable/controlled pseudorandomness and stable reference times so that, by default, the same content will be simulated each time.  This means that the two simulation output files should not change when the simulation is run again.

[uss_qualifier] Generate stable pseudorandom simulated RID data

---

monitoring/uss_qualifier/bin/visualize_configuration.sh
monitoring/uss_qualifier/reports/graphs.py
monitoring/uss_qualifier/reports/report.py
monitoring/uss_qualifier/requirements.txt
monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/nominal_planning.py
monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning_priority/nominal_planning_priority.py
monitoring/uss_qualifier/scenarios/uspace/flight_auth/validation.py
monitoring/uss_qualifier/suites/suite.py
monitoring/uss_qualifier/visualize_configuration.py

The nesting of suites, action generators, and scenarios in uss_qualifier can be complicated, along with which resources are used where.  This PR adds a small tool to visualize the breakdown of a test run via the data contained in its report.

[uss_qualifier] Add GraphViz visualization of a test run

---

monitoring/monitorlib/clients/scd_automated_testing.py
monitoring/uss_qualifier/resources/flight_planning/flight_planner.py
monitoring/uss_qualifier/resources/flight_planning/flight_planners.py
monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/nominal_planning.py
monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning_priority/nominal_planning_priority.md
monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning_priority/nominal_planning_priority.py
monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
monitoring/uss_qualifier/scenarios/uspace/flight_auth/validation.md
monitoring/uss_qualifier/scenarios/uspace/flight_auth/validation.py

This PR does a little bit of cleanup on SCD by renaming the tool used to tell USSPs to attempt to plan flights from `TestTarget` to `FlightPlanner`.  It also removes unneeded names for flights (flight IDs are sufficient) which simplifies a number of places somewhat.
Additionally, a critical missing `return True` is added to `test_steps.py::clear_area` -- without this return, a major portion of flight planning tests were being skipped as the attempt to clear the area appeared to have indicated that the test should not continue.  Fixing this revealed incorrect/missing documentation in the priority planning and U-space validation scenarios, as well as some shared logic, which is corrected in this PR.

[uss_qualifier] Rename TestTarget and simplify FlightPlanner

---

monitoring/uss_qualifier/scenarios/astm/netrid/nominal_behavior.py

This PR removes a left-over `name` argument in a `record_failed` call.

[uss_qualifier] Remove left-over record_failed key `name`

---

pkg/rid/models/api/v2/conversions.go
pkg/rid/server/v2/isa_handler.go
pkg/rid/server/v2/server.go
pkg/rid/server/v2/subscription_handler.go

Fourth batch of modifications.
This contains the adaptations of the RID v2 handlers and models conversion functions.
Do note that even though this is not apparent in this PR, those handlers as they are implemented pass the prober test (locally), with a few of them that needed adaptions.

#822 gRPC layer removal: adaptations of RID v2 handlers and models conversion

---

monitoring/uss_qualifier/scenarios/README.md
monitoring/uss_qualifier/scenarios/astm/netrid/nominal_behavior.md
monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/nominal_planning.md
monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/nominal_planning.py
monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning_priority/nominal_planning_priority.md
monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning_priority/nominal_planning_priority.py
monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
monitoring/uss_qualifier/scenarios/astm/utm/validate_shared_operational_intent.md
monitoring/uss_qualifier/scenarios/documentation/__init__.py
monitoring/uss_qualifier/scenarios/flight_planning/inject_successful_flight_intent.md
monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
monitoring/uss_qualifier/scenarios/uspace/flight_auth/validation.md

This PR cleans up and adds requirements for all of the checks in our currently-defined test scenarios.  In preparation for a more formal programmatic definition of requirements, a package-style format is adopted for requirement IDs.  Links to reference material relating to requirements are removed with the assumption that the requirements will be more explicitly defined (in a single place) in a future PR.
To avoid duplication and better align documentation with implementation, this PR also adds a feature where a test scenario documentation file may link to another file defining a test step -- this corresponds with calling a shared function to perform a common test step.  The two `test_steps.py` files contain examples of these shared test steps.
The `validate_shared_operational_intent` …

[uss_qualifier] Update documented requirements

---

monitoring/mock_uss/ridsp/routes_injection.py
monitoring/monitorlib/rid_automated_testing/injection_api.py
monitoring/uss_qualifier/resources/netrid/flight_data.py
monitoring/uss_qualifier/resources/netrid/flight_data_resources.py
monitoring/uss_qualifier/resources/netrid/simulation/adjacent_circular_flights_simulator.py
monitoring/uss_qualifier/resources/netrid/simulation/operator_flight_details.py
monitoring/uss_qualifier/scenarios/astm/netrid/nominal_behavior.py
monitoring/uss_qualifier/test_data/che/netrid/circular_flights.json

This PR switches from using monitorlib's manual RID injection API data objects to using the same objects from uas_standards.

[monitorlib] Use uas_standards for RID injection API

---

monitoring/monitorlib/infrastructure.py

When the uss_qualifier runs inside a container, connection to missing host may hang forever. This PR adds a default timeout to the test client to catch this use case. 15 seconds seemed reasonable in our context.

[uss_qualifier] Set timeout to uss qualifier client requests

---

monitoring/monitorlib/auth.py
monitoring/prober/aux_/test_version.py
monitoring/prober/rid/v1/test_isa_validation.py
monitoring/prober/rid/v1/test_token_validation.py
monitoring/prober/rid/v2/test_isa_expiry.py
monitoring/prober/rid/v2/test_isa_simple.py
monitoring/prober/rid/v2/test_isa_validation.py
monitoring/prober/rid/v2/test_token_validation.py
monitoring/prober/scd/test_constraint_simple.py
monitoring/prober/scd/test_constraints_with_subscriptions.py
monitoring/prober/scd/test_operation_references_error_cases.py
monitoring/prober/scd/test_operation_references_state_transition.py
monitoring/prober/scd/test_operation_simple.py
monitoring/prober/scd/test_operation_simple_heavy_traffic.py
monitoring/prober/scd/test_operation_simple_heavy_traffic_concurrent.py
monitoring/prober/scd/test_operation_special_cases.py
monitoring/prober/scd/test_operations_simple.py
monitoring/prober/scd/test_subscription_update_validation.py
pkg/api/ridv2/interface.gen.go

Seventh batch of modifications, those changes enable all tests to be validated with the new implementation.
- change from POST to GET the method to retrieve the token: because the generated code used to not check for the HTTP method, the POST call used to work, while this was actually not according to the OpenAPI definition of the dummy oauth provider
- aux API: do not retrieve anymore the version through the `as_string` subfield, which is a construct inherited from gRPC
- in all APIs: remove the error message exact comparison: now we have an error ID embedded, so we only do a substring check
- in all APIs: some validation messages changed due to the fact that it is not possible anymore for some fields to be missing (when they are specified as required they will be present but empty in …

#822 gRPC layer removal: adaptations of the prober tests

---

Makefile
interfaces/openapi-to-go-server/generate.py
pkg/api/ridv2/server.gen.go

Batch 8, a PR that is normally-sized for once.
This adds an option to the OpenAPI generation tool to add a prefix to the paths of the endpoints. This is useful for the RID v2 API. This is achieved by adding an optional syntax on the CLI.

#822 gRPC layer removal: add option for path prefix and use it for RID v2 API

---

monitoring/uss_qualifier/Makefile
monitoring/uss_qualifier/main.py
monitoring/uss_qualifier/reports/documents.py
monitoring/uss_qualifier/reports/templates/tested_requirement_set.html
monitoring/uss_qualifier/reports/templates/tested_requirements.html
monitoring/uss_qualifier/requirements/README.md
monitoring/uss_qualifier/requirements/astm/f3411/v19.md
monitoring/uss_qualifier/requirements/astm/f3411/v19/display_provider.md
monitoring/uss_qualifier/requirements/astm/f3411/v19/dss_provider.md
monitoring/uss_qualifier/requirements/astm/f3411/v19/service_provider.md
monitoring/uss_qualifier/requirements/astm/f3548/v21.md
monitoring/uss_qualifier/requirements/astm/f3548/v21/scd.md
monitoring/uss_qualifier/requirements/documentation.py
monitoring/uss_qualifier/requirements/interuss/automated_testing/flight_planning.md
monitoring/uss_qualifier/requirements/interuss/automated_testing/rid.md
monitoring/uss_qualifier/requirements/interuss/automated_testing/rid/injection.md
monitoring/uss_qualifier/requirements/interuss/automated_testing/rid/observation.md
monitoring/uss_qualifier/run_locally.sh
monitoring/uss_qualifier/scenarios/README.md
monitoring/uss_qualifier/scenarios/documentation/requirements.py
monitoring/uss_qualifier/scenarios/documentation/validation.py
monitoring/uss_qualifier/scenarios/uspace/flight_auth/validation.md

This PR adds programmatically-verified requirement documentation.
When a test scenario performs a check, it should generally specify a requirement that is not met when that check fails.  (Though specifying such a requirement is not currently mandatory).  If a check fails, the impacted USS should be able to clearly determine what requirement they have not fulfilled.  This PR ensures that each referenced requirement is documented to enable that discovery (even though the content of the requirements imposed by InterUSS is not populated in this PR).
These documentation requirements are documented in requirements/README.md and noted in and linked from scenarios documentation (scenarios/README.md).
In the second commit of this PR, the output of tested_requirements.html is grouped by requirement …

[uss_qualifier] Add requirement declarations

---

monitoring/uss_qualifier/Makefile
monitoring/uss_qualifier/documentation.py
monitoring/uss_qualifier/reports/documents.py
monitoring/uss_qualifier/reports/report.py
monitoring/uss_qualifier/requirements/documentation.py
monitoring/uss_qualifier/scenarios/README.md
monitoring/uss_qualifier/scenarios/astm/netrid/nominal_behavior.md
monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/nominal_planning.md
monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning_priority/nominal_planning_priority.md
monitoring/uss_qualifier/scenarios/documentation/autoformat.py
monitoring/uss_qualifier/scenarios/documentation/definitions.py
monitoring/uss_qualifier/scenarios/documentation/format_documentation.py
monitoring/uss_qualifier/scenarios/documentation/parsing.py
monitoring/uss_qualifier/scenarios/documentation/requirements.py
monitoring/uss_qualifier/scenarios/documentation/validate_documentation.py
monitoring/uss_qualifier/scenarios/documentation/validation.py
monitoring/uss_qualifier/scenarios/scenario.py
monitoring/uss_qualifier/scenarios/uspace/flight_auth/validation.md
monitoring/uss_qualifier/scripts/format_test_documentation.sh
monitoring/uss_qualifier/scripts/in_container/format_test_documentation.sh

The PR adds auto-formatting capability for test scenario documentation that is invoked with `make format` and verified in `make lint`.  The one auto-formatting operation implemented in this PR is automatically linking requirement references in test scenario documentation to the definition of the specified requirements (and this auto-formatting is applied to existing test scenario documentation).
To wrangle some dependencies, uss_qualifier/scenarios/documentation/__init__.py is split into uss_qualifier/scenarios/documentation/definitions.py and uss_qualifier/scenarios/documentation/parsing.py.  Note that git has a hard time showing a good diff when a file is both moved and then a new file added in its place, so please see just the first commit of this PR for a more accurate diff of the …

[uss_qualifier] Add documentation autoformatting

---

cloudbuild.yaml

In the longer term, we should harmonize our CI per #894, but in the mean time, our Cloud CI should at least match the operations developers would perform locally.  [In our Makefile](https://github.com/interuss/dss/blob/b36e2988b4567d5392f84b4abfd5d1e5b0d22387/Makefile#L52), `go_lint` uses version 1.26.0 of the golangci-lint image whereas cloudbuild.yaml uses older versions.  This PR updates cloudbuild.yaml to match our Makefile, though hopefully this change will be made obsolete in the near future by the resolution of #894.

[CI] Fix cloudbuild.yaml Go lint to match Makefile

---

monitoring/uss_qualifier/README.md
monitoring/uss_qualifier/configurations/README.md
monitoring/uss_qualifier/configurations/dev/self_contained_f3548.yaml
monitoring/uss_qualifier/configurations/personal/.gitignore
monitoring/uss_qualifier/configurations/personal/README.md
monitoring/uss_qualifier/scenarios/README.md
monitoring/uss_qualifier/suites/README.md

This PR improves uss_qualifier documentation by
1. Providing actionable usage instructions on the main uss_qualifier page
2. Moving architecture details into individual architecture components' (suite, scenario, resource, configuration) pages
3. Adding a complete, commented sample configuration (self_contained_f3548) for users to base their custom configurations off of

[uss_qualifier/docs] Improve uss_qualifier documentation

---

monitoring/monitorlib/scd_automated_testing/scd_injection_api.py

ClearAreaRequest needs to be removed from ClearAreaResponse, as per the yaml spec.

Removing ClearAreaRequest field from ClearAreaResponse as per given api

---

monitoring/uss_qualifier/action_generators/flight_planning/README.md
monitoring/uss_qualifier/action_generators/flight_planning/planner_combinations.py
monitoring/uss_qualifier/resources/flight_planning/flight_planner.py
monitoring/uss_qualifier/resources/flight_planning/flight_planners.py
monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/nominal_planning.md
monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/nominal_planning.py
monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning_priority/nominal_planning_priority.md
monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning_priority/nominal_planning_priority.py
monitoring/uss_qualifier/scenarios/scenario.py
monitoring/uss_qualifier/scenarios/uspace/flight_auth/validation.md
monitoring/uss_qualifier/scenarios/uspace/flight_auth/validation.py
monitoring/uss_qualifier/suites/astm/utm/f3548_21.yaml
monitoring/uss_qualifier/suites/uspace/flight_auth.yaml

Currently, the only test resource available to test scenarios for defining USSs that support flight planning (scd.yaml) is `FlightPlannersResource`, which specifies a list of flight planning USSs (flight planners).  This PR adds an alternate resource type: the singular `FlightPlannerResource` specifying exactly one flight planner.  This makes simple test scenario definitions clearer (each individual role can be defined explicitly), and it makes the FlightPlannerCombinations action generator much clearer: it produces multiple sets of FlightPlannerResources from a single FlightPlannersResource.  The latter behavior is now more clearly documented in a README.md, added in this PR.

[uss_qualifier] Add single FlightPlannerResource

---

.github/workflows/dss-publish.yml
Makefile
RELEASE.md
scripts/tag.sh

This PR adds the ability to specify a full semantic version (including a "pre-release" suffix) for a desired DSS release tag, per [semantic versioning](https://semver.org).  The format for `make tag` is correspondingly updated, as is the documentation in RELEASE.md (also including cleanup of unrelated content at the bottom).

[release] Support full semantic version in release tags

---

build/dev/check_dss.sh
build/dev/check_scd_clear.sh
build/dev/check_scd_write.sh
build/dev/check_subs.sh
build/dev/extract_json_field.py
build/dev/read_scd_constraint_reference.sh
build/dev/read_scd_operational_intent_reference.sh
build/dev/read_scd_subscription.sh

Currently, some check scripts for a local DSS deployment are broken (due to #901 correcting the HTTP method for dummy auth), and the `jq` dependency is unnecessary.  This PR corrects those two issues in preparation for incorporating these checks into an additional step in the CI (in another PR).

[dss/dev] Clean up local checks

---

Makefile
build/dev/wait_for_local_dss.sh
monitoring/mock_uss/run_locally_base.sh
monitoring/mock_uss/run_locally_geoawareness.sh
monitoring/mock_uss/start_all_local_mocks.sh
monitoring/mock_uss/stop_all_local_mocks.sh
monitoring/mock_uss/wait_for_mock_uss.sh
monitoring/uss_qualifier/scripts/test_docker_fully_mocked.sh

Currently, a user is required to run a number of separate commands to bring up various pieces of a local system that can be tested by uss_qualifier's standard local test.  This PR adds two commands to easily bring up the mock_uss instances required by the standard local uss_qualifier test (`make start-uss-mocks` and `make stop-uss-mocks`) and harmonizes approaches to managing these mocks.
It also adds a small check at the end of uss_qualifier's standard automated tests (used in CI) to verify that the uss_qualifier report indicated successs.

[monitoring/mock_uss] Improve management capabilities of local USS mocks

---

monitoring/mock_uss/scdsc/database.py
monitoring/mock_uss/scdsc/routes.py
monitoring/mock_uss/scdsc/routes_injection.py
monitoring/mock_uss/start.sh
monitoring/monitorlib/clients/scd.py
monitoring/monitorlib/clients/scd_automated_testing.py
monitoring/uss_qualifier/configurations/configuration.py
monitoring/uss_qualifier/configurations/dev/f3548/nominal_planning_priority.yaml
monitoring/uss_qualifier/configurations/dev/resources.yaml
monitoring/uss_qualifier/reports/graphs.py
monitoring/uss_qualifier/resources/flight_planning/__init__.py
monitoring/uss_qualifier/resources/flight_planning/flight_planner.py
monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/nominal_planning.py
monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning_priority/nominal_planning_priority.md
monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning_priority/nominal_planning_priority.py
monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
monitoring/uss_qualifier/scenarios/astm/utm/validate_shared_operational_intent.md
monitoring/uss_qualifier/scenarios/definitions.py
monitoring/uss_qualifier/scenarios/documentation/requirements.py
monitoring/uss_qualifier/scenarios/flight_planning/successfully_activate_flight.md
monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
monitoring/uss_qualifier/scenarios/uspace/flight_auth/validation.py

This PR partially completes the unfinished nominal planning priority test scenario by activating the high-priority flight.
This required behavioral changes in mock_uss's scd functionality, and some logging was added to help troubleshoot, though it should be helpful in the future as well.  The changes to the inject_flight handler appear very large if whitespace is not omitted because most of the routine is placed into a try/finally block to ensure that the locked flight is always released.  Flight locking is added in order to mutate the flight in a process-safe way.
A single nominal_planning_priority configuration is added to run just that one scenario without the need for a suite.  This was useful for debugging behavior, but it will also serve as the first example of how to run a single …

[uss_qualifier] Add activation to priority planning scenario

---

monitoring/atproxy/atproxy.postman_collection.json
monitoring/atproxy/requests.py
monitoring/atproxy/routes.py
monitoring/atproxy/routes_rid_injection.py
monitoring/atproxy/routes_rid_observation.py
monitoring/atproxy/routes_scd.py
monitoring/atproxy/run_locally.sh

This PR adds support for SCD injection endpoints to atproxy, as well as entries in the Postman collection to verify behavior.  All SCD injection endpoints in this PR were tested successfully using the Postman collection.
Note that atproxy is mostly not included in continuous integration tests.  I've added #925 to address this eventually.

[monitoring/atproxy] Add SCD injection endpoints to atproxy

---

CONTRIBUTING.md
monitoring/mock_uss/Makefile
monitoring/monitorlib/Makefile
monitoring/uss_qualifier/Makefile

In addition to adding the style guide, this PR also explicitly pins the version of the Black formatter for Python as initially this PR (which changes one line of a .md file) was failing Python formatting checks because the `latest_version` tag of `pyfound/black` was rev'd to a version that detects problems with the current repo content.  We should explicitly move between `pyfound/black` versions in the future.  Added #932 to track this.

[docs] Add reference to Python style guide

---

monitoring/mock_uss/config.py
monitoring/mock_uss/geoawareness/routes_geoawareness.py
monitoring/mock_uss/riddp/routes_behavior.py
monitoring/mock_uss/riddp/routes_observation.py
monitoring/mock_uss/ridsp/routes_behavior.py
monitoring/mock_uss/ridsp/routes_injection.py
monitoring/mock_uss/ridsp/routes_ridsp.py
monitoring/mock_uss/scdsc/routes_injection.py
monitoring/mock_uss/scdsc/routes_scdsc.py
monitoring/monitorlib/clients/scd.py
monitoring/monitorlib/scd.py
monitoring/uss_qualifier/main.py
monitoring/uss_qualifier/reports/report.py

As part of #925, mock_uss needs to be restructured a bit to prepare for adding functionality to act as a backend implementation client for atproxy.  Toward that end, this PR:
1. Explicitly prefixes all Flask-route-decorated functions to avoid function name conflicts between different capabilities (the function names of Flask route handlers must be globally unique within a Flask application)
2. Separates SCD handlers into a small route handler that parses inputs and returns responses, and a function that actually performs the logic -- only this latter function will be used by the backend implementation client capability of mock_uss to be added in a future PR
3. Improves error messages in two places
4. Fixes a bug where uss_qualifier would always print to screen/log that tests were …

[mock_uss] Prepare mock_uss for backend implementation client functionality

---

.github/workflows/dss-publish.yml
build/build.sh

This PR adapts the current release workflow to update the `latest` tag along the version.
Script was tested locally using [my personal account](https://hub.docker.com/repository/docker/michaelbarroco/dss/tags?page=1&ordering=last_updated): 
```sh
DOCKER_URL="michaelbarroco" DOCKER_UPDATE_LATEST=true build/build.sh
```

Publish latest tag when making a release

---

deploy/infrastructure/modules/terraform-aws-dss/main.tf

This PR adds a missing variable flag to `terraform-aws-dss`.
The variable flag should have been added as part of #944

[tf-aws] Add missing image_pull_secret variable

---

pkg/scd/operational_intents_handler.go

This is a quick fix applied to persist notify_for_constraints. 
Closes #952

fix: persist notify_for_constraints

---

Makefile
build/dev/docker-compose_dss.yaml
build/dev/haproxy_local_setup.sh
build/dev/migrate_local_db.sh
build/dev/mutli_node_local_dss.md
build/dev/probe_locally.sh
build/dev/run_locally.sh
build/dev/standalone_instance.md
build/dev/startup/core_service.sh
build/dev/wait_for_local_dss.sh
test/README.md

These updates for the docker compose updates to the container naming convention changes in Docker V2.

Use docker compose v2 instead of docker-compose v1

---

build/deploy/base.libsonnet

To support Kubernetes v1.25, the following changes are necessary:
- `metadata.clusterName` has been [removed](https://github.com/kubernetes/kubernetes/pull/109602)
- `PodDisruptionBudget` version `v1beta1` is [no longer served](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125).
- `ManagedCert` version `v1beta1` has been deprecated.

[deployment] Update removed/deprecated resources and fields for Kubernetes v1.25

---

README.md
interfaces/rid/README.md

Addresses Issue #969 and #956 .
Proposed fix is to link directly to the tags in the external repo.  Might not be the best thing, but arguably better than the broken links in current README.

Update F3411 API links to point at tags in uastech repo.

---

pkg/scd/models/operational_intents.go
pkg/scd/store/cockroach/operational_intents.go

The current implementation of the SCD handlers that return operational intents will always return an USS availability state "Unknown". 
This PR implements the retrieval of the availability state of the operational intent's managing USS and embed it in the operational intent representation.
Please let me know if the approach taken is not correct, I have no experience with the cockroach part of the codebase.
~Note: as this is failing tests, I'm putting the PR back to draft until fixed.~

[SCD] Populate uss_availability field of operational intents

---

pkg/scd/models/operational_intents.go
pkg/scd/operational_intents_handler.go

The current implementation of the SCD handlers that create or update operational intents do not exclude the OVNs of accepted operational intents of down USSes from the required OVNs as it is required to by the standard.
This PR fixes this.

[SCD] Do not require key for accepted op intents of down USSes

---

pkg/scd/subscriptions_handler.go

While writing a scenario for the `uss_qualifier` I ran into a situation where the DSS does not use the proper HTTP code when the requested are is too large for subscription queries in the SCD context.
As per [specification](https://github.com/astm-utm/Protocol/blob/v1.0.0/utm.yaml#L2936), in this situation, we should receive a 413 code, and not the observed 500 one.
The location in the code was found through the following DSS logs:
```
2024-01-11T13:51:43.660Z	error	errors/errors.go:81	Error during unary server call	{"error_id": "E:7998749e-a7f4-4a2b-a39c-46d7dac2e222", "stacktrace": "Got an unexpected error\n --- at /app/pkg/scd/subscriptions_handler.go:443 (Server.QuerySubscriptions) ---\nCaused by: Error searching Subscriptions in repo\n --- at /app/pkg/scd/subscriptions_handler.go:414 …
```

[scd] return proper http code for too big area search on the SCD subscriptions endpoint

---

build/dev/probe_locally.sh
pkg/scd/subscriptions_handler.go
test/migrations/rid_db_post_migration_e2e.sh

Discovered that the `version` of a subscription was plainly ignored when writing some tests for the deletion endpoint.
With the present fix we obtain the expected failure when:
- the version is missing
- the version is wrong
While the deletion functionality still works when the provided version is correct.

[scd] check subscription version is present and correct when deleting

---

cmds/core-service/main.go
cmds/dummy-oauth/main.go

This PR adds server timeouts to address [this concern](https://docs.bearer.com/reference/rules/go_gosec_http_http_slowloris/).

[security] Add server timeouts

---

pkg/models/models.go
pkg/models/models_test.go

The OpenAPI specification for the [SCD endpoints](https://github.com/astm-utm/Protocol/blob/v1.0.0/utm.yaml#L120) specifies that we should use a UUID V4 of the RFC4122 variant. It provides a regexp(*) for validating the UUIDs in an unambiguous way.
However, In the context of SCD, the current implementation allows the use of IDs that don't conform to the V4-RFC4122 variant, such as `00000179-e36d-40be-d38b-eca6ca350000`
This might be problematic if other implementations chose to enforce this more strictly:
- a client may successfully create an entity on this DSS implementation
- a client will then expect other DSS's for the relevant area to reply to requests, which said DSS's might reject because the requested IDs are not valid
More generally, a request for creating an entity should either …

[apis] models.IDFromString strictly check for RFC 4122 variant of the V4  UUID format

---

cmds/core-service/main.go

core-service uses an indicator file to communicate service readiness, but previously didn't detect an extreme edge case where closing that file generated an error.  This PR fixes that extreme edge case.

[core-service] Close indicator file

---

pkg/scd/store/cockroach/store.go

Documentation link in error log for migration is not going to correct section of dss/build readme file (Upgrading Database Schemas) because of a typo in upgrading word.

Fix documentation link typo in error log for CheckCurrentMajorSchemaVersion error 

---

pkg/scd/store/cockroach/operational_intents.go

For what I believe are historical reasons (entity cells used to be in a separate table from the entities themselves rather than in a column of the entity), the S2 cells for an operational intent are currently retrieved separately and explicitly for each individual operational intent even though the cells had already been retrieved in the initial query for operational intent information.  This resulted in an enormous number of additional queries -- one for each operational intent result -- which would cause, e.g., an operational intent search to perform 200+ SQL queries if the search returned 200 operational intents.  All of these additional queries are unnecessary because each entity's S2 cells are already retrieved on the initial query.
This PR fixes that problem by simply deleting the …

Remove redundant S2 cells queries for operational intents

---

pkg/scd/operational_intents_handler.go

When upserting an OIR with missing keys, DSS currently returns the full reference for the missing entity, including the OVN. Returning the OVN could be a problem because an USS may create a conflicted OIR without having the get the OIR details from other USS.
This PR hides the OVNs from the missing entities that are not owned from the requiring manager, matching the behavior of the GET and QUERY endpoints.
**Old upsert return:**
`
{
"message": "Current OVNs not provided for one or more OperationalIntents or Constraints",
"missing_operational_intents": [
{
"id": "46d06891-38d7-46dd-be98-2f617810f15e",
...
"ovn": "t6Or7spPB0cJ8AV0zN088GBtfHTw6m4qZG9jan3T870_",
....
}
]
}
`
**New upsert return:**
`
{
"message": "Current OVNs not provided for one or more OperationalIntents or Constraints", …

[dss][scd] Removing OVN from missing entities when upserting OIR

---

.dockerignore
Dockerfile
cmds/core-service/main.go

As reported by #1048 , `build/build.sh`  always classifies built/released images and binaries as dirty. This PR fixes this issue by copying all files to the intermediary `build` layer.
A redundant `go install` step is removed in the Dockerfile since it is already run in the Makefile and there is no clear benefit in caching non-executable packages there.
`**/.terrafom` are ignored since terraform providers binaries are cached there and the size may quickly be few 100s of megabytes, make the context slow to load when building the docker image.
The result is correctly reflected by the CI. No `-dirty` suffix is observed on the commit and version injected in the binary build: https://github.com/interuss/dss/actions/runs/9846450148/job/27184246127?pr=1053#step:7:281

[dss] Ensure clean workspace for releases

---

.gitmodules
build/dev/read_version.sh
build/dev/startup/core_service.sh
cmds/core-service/main.go
pkg/api/versioningv1/interface.gen.go
pkg/api/versioningv1/server.gen.go
pkg/api/versioningv1/types.gen.go
pkg/versioning/server.go
pkg/versioning/server_test.go

Adds the versioning API to the DSS, according to https://github.com/interuss/automated_testing_interfaces/tree/main/versioning.
This is done by:
- adding a submodule that points to the versioning endpoint spec [repository](https://github.com/interuss/automated_testing_interfaces)
- running the generator, moving the generated files to a relevant place and checking them into git
- serving the new route and returning the current binary version for any requested identity.
The endpoint was tested locally via the `build/dev/read_version.sh` test script.
resolves #1047

[versioning] add new versioning endpoint

---

.github/workflows/ci.yml
Makefile
build/dev/dss_probing_qualifier_config.yaml
build/dev/qualify_locally.sh

To increase test coverage, we add a step to the CI that will run the qualifier against the DSS version built from the current PR.
Notes:
- this currently only runs "single instance tests", as, to the best of my understanding, only a single DSS instance is started in CI (therefore, only a single DSS is configured)
- this does not run any CRDB-specific checks (they are skipped) 
- the configuration was obtained by running the qualifier with the `--config-output` option, with the following modifications:
- removal of the second DSS
- add `has_private_address: true` to dss resource specifications (otherwise the qualifier fails on resource initialisation)
- set `uss1: all_astm_dss_requirements` in the `participant_requirements` artifacts section
Test plan:
This worked both locally when running …

[ci] run the uss-qualifier as part of the CI

---

pkg/errors/errors.go
pkg/scd/operational_intents_handler.go

Adds the missing OVN check to the OIR deletion logic.
This is a first step towards fixing #1081 (it covers OIRs)
Test plan: a DSS version built from this PR passes the new [qualifier scenario](https://github.com/interuss/monitoring/pull/761) designed to detect this kind of issue.

[scd] oir deletion now checks for OVN correctness

---

pkg/scd/constraints_handler.go

Add a check for the provided OVN before deleting constraint references.
Once #1082 is merged, this will close #1081 
Test plan: a DSS built from this PR was used as a target for [this scenario](https://github.com/interuss/monitoring/pull/762) and behaved properly.

[scd] cr deletion now checks for OVN correctness

---

pkg/scd/operational_intents_handler.go

A first small step towards #1088.
This takes care of moving the parameter validation to a submethod. It is not yet improving anything with respect to the core business logic, but allows readers to more directly focus on the code of what `upsertOperationalIntentReference` does.
Note about the usage of the `stacktrace` library and our dependency on error codes: as we use the error codes to decide what HTTP response to send back, it is important that we properly propagate them when we move logic one or several layers of method calls.

[scd] factor out parameter validation for oir upsert method

---

pkg/scd/operational_intents_handler.go

Moves the checks that compare the requesting manager to the one of the (possibly) existing OIR to a submethod.
Note the usage of `stacktrace.GetCode(err)` and `stacktrace.PropagateWithCode()`: I'm not sure we have a more elegant solution such as we had in #1089 if we want to avoid this.

[scd] factor out parameter validation against previous OIR

---

pkg/scd/operational_intents_handler.go

Another step towards #1088 
Moves the logic which validates the provided `key` parameter, and which provides details for missing entries to the caller, to a separate method.

[scd] oir upsert factor out key validation

---

pkg/scd/operational_intents_handler.go

[scd] oir upsert: factor out determination of subscriptions to notify

---

pkg/scd/operational_intents_handler.go

These checks are now done explicitly and early.
This change of behavior was split off from #1094 
It is part of the refactors for #1088

[scd] oir upsert: check uss base URL and if both subscription ID and implicit request are specified

---

pkg/scd/operational_intents_handler.go

Also moves the implicit subscription URL check to parameter validation
another step for #1088

[scd] oir upsert: factor implicit subscription creation

---

pkg/scd/operational_intents_handler.go

[scd] oir upsert: factor out extension and validation of existing subscription

---

pkg/scd/operational_intents_handler.go

This is a rework of #1057 after most changes for #1088 have landed.
The DSS built from this PR successfully passed the new qualifier's [implicit subscription handling scenario](https://github.com/interuss/monitoring/pull/720), although that scenario still needs to be extended to cover all corner cases.
The PR is open for review, as it addresses #1056

[scd] properly cleanup implicit sub on oir update

---

pkg/scd/operational_intents_handler.go

PR stacked on top of #1095 and #1100: please only consider beb2042b3308c689bc7b27d572fb23dc81de4dbe for review.
Continuation of #1078 
This enables storing all past OVNs in the DB.

[scd] Store past OVNs on operational intents upsert

---

.gitmodules
interfaces/openapi-to-go-server/example/api/scd/interface.gen.go
interfaces/openapi-to-go-server/example/api/scd/types.gen.go
pkg/api/auxv1/interface.gen.go
pkg/api/scdv1/interface.gen.go
pkg/api/scdv1/types.gen.go
pkg/scd/models/constraints.go
pkg/scd/models/operational_intents.go

Step towards addressing #1078.
`make apis` was ran to regenerate the `.gen.go` files.

[interfaces/astm-utm-protocol] Target interuss/astm-utm-protocol repo as submodule and regen apis files

---

pkg/rid/application/isa.go
pkg/rid/application/isa_test.go
pkg/rid/repos/isa.go
pkg/rid/store/cockroach/garbage_collector_test.go
pkg/rid/store/cockroach/identification_service_area.go
pkg/rid/store/cockroach/identification_service_area_test.go
pkg/rid/store/cockroach/identification_service_area_v3.go
pkg/rid/store/cockroach/store_test.go
pkg/sql/utils.go

Optionally append `FOR UPDATE` on read requests for situations where the caller's intention is to mutate the record in the same transaction.
Part of #814

[dss/RID] GetISA: optional forUpdate flag to allow for early locking

---

pkg/scd/operational_intents_handler.go

The early locking already happens for insertions/mutations, there is no reason not to do it for deletions.
Part of #814

[dss/SCD] early subscription lock for OIR deletions

---

Makefile
build/deploy/schema-manager.libsonnet
build/dev/haproxy_local_setup.sh
build/dev/startup/rid_bootstrapper.sh
build/dev/startup/scd_bootstrapper.sh
cmds/core-service/README.md
cmds/db-manager/main.go
cmds/db-manager/migration/migrate.go
deploy/services/helm-charts/dss/templates/schema-manager.yaml
go.mod
go.sum

This PR refactors the `db-manager` command to support subcommands (notably for #1116).
- The existing `db-manager` logic is now defined as the `migration` subcommand. Various updates of scripts, deployment files, and documentations are made in that regard.
- Introduce use of spf13/cobra and spf13/pflag libraries to support this.
- Note that not all flags are migrated to using spf13/pflag, however the existing ones that use `flag` are still supported (notably for the cockroachdb flags).
- `go mod tidy` was ran.
- The diff is unfortunately not very readable, however here is a change overview that should help review:
- `cmds/db-manager/main.go` is a new file
- `cmds/db-manager/main.go` was moved to `cmds/db-manager/migration/migration.go` and adapted:
- panics are replaced by returning …

[cmd] Enable db-manager CLI to support subcommands

---

Makefile
cmds/db-manager/cleanup/README.md
cmds/db-manager/cleanup/evict.go
cmds/db-manager/cleanup/scd-evict.go
cmds/db-manager/main.go
pkg/scd/repos/repos.go
pkg/scd/store/cockroach/operational_intents.go
pkg/scd/store/cockroach/operational_intents_test.go
pkg/scd/store/cockroach/store_test.go
pkg/scd/store/cockroach/subscriptions.go
pkg/scd/store/cockroach/subscriptions_test.go

Addresses #1074 
This PR adds a CLI tool `db-manager scd-evict` that enables deletion of expired entities. See enclosed README for more details on its usage.
Do note the approach taken when entities do not have end times: the last update times are used.

[cmds][scd/store] Add 'db-manager scd-evict' subcommand enabling listing and deletion of expired SCD entities

---

cmds/db-manager/cleanup/evict.go

As per discussion during InterUSS weekly.

[cmd] Add warning log about performance impact in 'db-manager evict'

---

pkg/scd/models/models.go
pkg/scd/models/models_test.go
pkg/scd/models/subscriptions.go
pkg/scd/operational_intents_handler.go

Final step towards addressing #1078.
Still pending testing with upcoming uss_qualifier test scenario, but review welcomed in the meantime in any case.

[scd] Enable USSs to request an OVN for operational intents

---

.github/workflows/codeql.yml

This PR includes the automatically-generated/recommended settings to enable CodeQL analysis under Code scanning in the Security tab in GitHub.

Enable CodeQL analysis

---

build/README.md
deploy/README.md
deploy/operations/README.md
deploy/operations/troubleshooting.md

As part of the effort to streamline deployment/operations documentation, this PR moves troubleshooting information from the `build` README to a page in `deploy/operations`.  Trailing spaces are auto-removed by the IDE.

[docs] Move troubleshooting into operations

---

deploy/operations/pooling.md

#1161 move of the pooling documentation didn't include the update of the image paths. This PR fixes it.

[docs] Fix image references

---

build/dev/read_pool_info.sh
cmds/core-service/main.go
interfaces/aux_/aux_.yaml
pkg/api/auxv1/interface.gen.go
pkg/api/auxv1/server.gen.go
pkg/api/auxv1/types.gen.go
pkg/aux_/pool.go
pkg/aux_/server.go
pkg/datastore/connectParameters.go
pkg/datastore/datastore.go
pkg/datastore/flags/flags.go
pkg/errors/errors.go

A key piece of information about the pool of DSS instances to which a particular DSS instance is connected is the identity of the DSS Airspace Representation data store.  The technical embodiment of this concept is easily accessible in CockroachDB as the Cockroach cluster ID -- if two DSS instances' CRDB nodes have the same cluster ID, then those DSS instances are nearly certain to be part of the same pool/cluster.  This concept is also present in Yugabyte, though somewhat harder to access.
Providing access to this information is likely to be very useful as an easy verification that two DSS instances are part of the same pool, and can partially address #1171.
This PR was tested with read_pool_info.sh using the standard local CRDB-based deployment, as well as the local Yugabyte-based …

[aux] Add access to DAR ID via aux API

---

deploy/operations/certificates-management/ca_pool.py
deploy/operations/certificates-management/cluster.py
deploy/services/helm-charts/dss/templates/_volumes.tpl
interfaces/aux_/aux_.yaml
pkg/api/auxv1/interface.gen.go
pkg/api/auxv1/server.gen.go
pkg/api/auxv1/types.gen.go
pkg/api/ridv1/interface.gen.go
pkg/api/scdv1/interface.gen.go
pkg/aux_/accepted_ca_certs.go
pkg/aux_/instance_ca_certs.go
pkg/aux_/utils.go
pkg/datastore/connectParameters.go

Contributing to #1140, this PR add an endpoint listing current CAs in the pool, and the CA(s) of the instance.
Idea would be to use that list of certificates to join a pool.
It doesn't include security, assuming thoses are public.
I only updated the yugabyte script to expose the CA of the instance, it won't works for cockroachdb.

[aux] Add CAs endpoint

---

pkg/rid/store/cockroach/garbage_collector.go
pkg/rid/store/cockroach/garbage_collector_test.go

Fix  #1249 
Don't return an error when an ISA/subscription has been deleted (looking at the code It doesn't seems to make sense) + add tests to validate that more than one subscription/ISA is removed. (And without the fix, the test indeed doesn't pass).

[rid] Fix garbage collector by deleting multiples entries at a time

---

pkg/auth/auth.go
pkg/aux_/server.go
pkg/rid/server/v1/server.go
pkg/rid/server/v2/server.go
pkg/scd/server.go
pkg/versioning/server.go

I tried automatically and fail, so I did a manual pass to remove potential `stacktrace.Propagate(nil, ...` calls
This should remove most of them, the main potential worrying one is in the authentication part.
Effort towards #1255

Remove potential nil error to stacktrace.Propagate
