README.md
Or something more to that affect.
=> grammatical typo in first line :-)

datanode/src/storage_api.py, datanode/src/storage_api_test.py
Based on discussion in #12 , creating a new "default" route to the API
=> Added '/' route to API

datanode/src/storage_api.py, datanode/src/storage_api_test.py
This fixes issue #34 , as it allows an optional parameter to /slippy to support path/polygon (defaulted to the current capability of point). 
This will be published as 1.1.0 once the multigrid operations are added, but for now is version 1.0.2.004 internally. Swaggerhub draft changes for 1.1.0 are here:
https://app.swaggerhub.com/apis/InterUSS_Platform/data_node_api/1.1.0#/
=> slippy non-breaking api changes to support path/polygon

assets/swaggerhub_api.yaml
This PR updates the SwaggerHub yaml spec to match intentions (no substantive changes intended) and to fill in example values and sandbox config.
=> Updated SwaggerHub spec

datanode/docker/Dockerfile_storageapi, datanode/src/storage_api.py, datanode/src/storage_api_test.py, datanode/src/storage_interface.py, datanode/src/storage_interface_test.py, datanode/src/updating.md, datanode/src/uss_metadata.py
This PR addresses a number of issues in the TCL4 branch as well as fixing and improving some tests that weren't testing the intended features.  Major improvements include improved validation of both operators and operations, and more informative error messages when requests can't be fulfilled.
=> Improve validation and error messages

README.md, config/README.md, config/apply-certs.sh, config/build.sh, config/make-certs.py, config/templates/cockroachdb-statefulset-secure.yaml, config/values.yaml.template
* Edit readme to better reflect options for running a DSS. 
* Fix some inconsistencies in the docs
* Fix make-certs.py to use combined certs so we don't need to share private keys.
=> finish readme

.gitignore, Makefile, azure-pipelines.yaml
Please note that test results are not exported, yet. I'll leave that to a follow-up PR.
=> [ci] Integrate e2e tests

config/README.md, config/apply-certs.sh, config/build.sh, config/values.yaml.template
Cleanup some scripts and readme since recent changes
=> cleanup startup scripts

monitoring/prober/test_isa_simple.py, monitoring/prober/test_subscription_simple.py, monitoring/prober/test_subscription_validation.py, monitoring/prober/test_token_validation.py
Annotates the specific tests that fulfills specific requirements from the ASTM Standard.
@BenjaminPelletier
=> Annotate Tests with Standards Compliace Code

test/interoperability/Dockerfile, test/interoperability/clients.py, test/interoperability/interop.py, test/interoperability/interop_test_suite.py, test/interoperability/requirements.txt
A test suite used to for testing the interoperability between DSS based on the ASTM standards.
Ensuring that every action taken in one DSS are reflected in the other DSSs
#89
=> Interoperability Test Suite

monitoring/prober/test_isa_validation.py, pkg/dss/geo/s2.go
=> Error out when extent footprint is not valid coordinates

config/run-locally.sh
cd into base dir and before running
check if all processes exists and prints message before waiting
=> Make run-locally.sh more user friendly

build/deploy/alertmanager.libsonnet, build/deploy/dss.libsonnet, build/deploy/grafana.libsonnet, build/deploy/metadata_base.libsonnet
Also reformat grafana.libsonnet
=> Add Alertmanager as optional deployment

build/README.md, build/deploy/grpc-backend.libsonnet, build/deploy/http-gateway.libsonnet, build/deploy/metadata_base.libsonnet, cmds/grpc-backend/main.go, cmds/http-gateway/main.go
Adding the Profiling capability for grpc-backend and http-gateway and
updating README for instructions to start the profiling services
=> Adding the Profiling capability for grpc-backend and http-gateway. 

build/deploy/prometheus.libsonnet
This was accidentally removed with https://github.com/interuss/dss/commit/502b13129a011ab956cd48dae3c26a91761257b1
=> Re add the external label for federation

Makefile, build/dev/check_dss.sh, build/dev/run_locally.sh, test/docker_e2e.sh
This PR generally makes scripts a little more friendly by printing more useful/actionable error messages, fixing cross-platform issues so that they work on Mac as well as Linux, and generating an additional debugging artifact.
=> Make scripts friendlier

pkg/api/v1/ridpb/conversions.go, pkg/dss/geo/s2.go, pkg/dss/geo/s2_test.go, pkg/dss/models/geo.go, pkg/dss/rid/models/identification_service_area.go, pkg/dss/rid/models/subscriptions.go, pkg/dss/rid/server_test.go, test/docker_e2e.sh
Currently, our geo library operates on RID-specific protobuf objects.  This PR introduces geo business objects, along with conversions to and from the RID-specific objects, to prepare for reuse of the geo library with SCD.
=> Add geo business objects

Makefile, README.md, test/README.md, test/interoperability/Dockerfile, test/interoperability/README.md
This PR attempts to document the current testing we have in place and how developers can reproduce it locally (especially the tests for continuous integration).
=> Improve testing documentation, clean Makefile

pkg/api/v1/ridpb/conversions.go, pkg/api/v1/scdpb/conversions.go, pkg/dss/geo/s2.go, pkg/dss/models/geo.go
This PR provides conversion functions for SCD models <-> DSS models.
=> Add conversion functions for SCD

build/deploy/cockroachdb.libsonnet, build/deploy/metadata_base.libsonnet
=> upgrade crdb to v19.6.2 as part of migration to 20.1

pkg/scd/operations_handler.go
=> move to grpc status

build/deploy/prometheus.libsonnet
=> Fix prom service

pkg/errors/errors.go
=> [errors] Always log internal error messages

monitoring/prober/scd/test_operations_simple.py, pkg/scd/operations_handler.go
=> [scd] Fix OVN leak on PUT

build/README.md, monitoring/prober/aux/test_token_validation.py, monitoring/prober/infrastructure.py
This PR adds and clarifies a bit of build documentation and also fixes a test that was incorrectly dependent on using the dummy OAuth server.
=> Clean up issues found during deployment projects

build/README.md, build/apply-certs.sh, build/deploy/examples/minimum/main.jsonnet, build/make-certs.py, scripts/git/commit.sh
This PR addresses a number of small issues encountered by a user trying to deploy via the Tanka/Kubernetes instructions.
=> Improve deployment experience

Makefile, RELEASE.md, scripts/release.sh
=> [build] Introduce release target

cmds/http-gateway/main.go, pkg/api/v1/auxpb/aux_service.proto
This PR simplifies, harmonizes, and better-documents error messages, especially in off-nominal circumstances.
=> Harmonize and document off-nominal error responses

build/README.md
This PR fixes an error in the deployment documentation regarding creation of GCP CRDB IP addresses and adds some additional documentation.
=> Fix and improve deployment documentation

pkg/rid/models/subscriptions.go, pkg/rid/server/subscription_handler.go, pkg/rid/store/cockroach/identification_service_area.go, pkg/rid/store/cockroach/store.go, pkg/rid/store/cockroach/store_test.go, pkg/rid/store/cockroach/subcriptions_v3.go, pkg/rid/store/cockroach/subscriptions.go
#349
Changes
1. Add writer file to subscription object
2. Create function returning SubscriptionRepo based on store version
3. Update Subscription handler to pass locality value
4. Move previous /cockroach/subscription.go to /cockroach/subscription_v3.go. This file will be delete after rid db is migrated to v3.1.
=> Update update sql script to write writer field for Subscriptions table

Makefile, azure-pipelines.yaml
=> [build] Factor run-locally.sh under test

monitoring/interoperability/README.md, monitoring/interoperability/interop_test_suite.py, monitoring/monitorlib/README.md, monitoring/monitorlib/rid.py, monitoring/monitorlib/scd.py, monitoring/prober/README.md, monitoring/prober/aux_/test_token_validation.py, monitoring/prober/aux_/test_version.py, monitoring/prober/rid/common.py, monitoring/prober/rid/test_isa_expiry.py, monitoring/prober/rid/test_isa_simple.py, monitoring/prober/rid/test_isa_validation.py, monitoring/prober/rid/test_subscription_isa_interactions.py, monitoring/prober/rid/test_subscription_simple.py, monitoring/prober/rid/test_subscription_validation.py, monitoring/prober/rid/test_token_validation.py, monitoring/prober/scd/test_constraint_simple.py, monitoring/prober/scd/test_constraints_with_subscriptions.py, monitoring/prober/scd/test_operation_references_error_cases.py, monitoring/prober/scd/test_operation_references_state_transition.py, monitoring/prober/scd/test_operation_simple.py, monitoring/prober/scd/test_operation_simple_heavy_traffic.py, monitoring/prober/scd/test_operation_simple_heavy_traffic_concurrent.py, monitoring/prober/scd/test_operation_special_cases.py, monitoring/prober/scd/test_operations_simple.py, monitoring/prober/scd/test_subscription_queries.py, monitoring/prober/scd/test_subscription_simple.py
Prober uses some RID and SCD constants and functions that will be useful to other monitoring tools.  This PR factors them out into monitorlib with no functional changes intended.
=> Refactor common RID & SCD tools into monitorlib for reuse beyond prober

monitoring/monitorlib/fetch/rid.py, monitoring/monitorlib/rid.py, monitoring/tracer/uss_receiver/routes.py, monitoring/tracer/uss_receiver/templates/rid_poll.html
This small PR adds the ability to request experimental enhanced RID details when requesting RID flight_details queries in tracer_subscribe.
=> [tracer] Enable enhanced_details query from tracer

go.sum, monitoring/loadtest/locust_files/ISA.py, monitoring/loadtest/locust_files/Sub.py, monitoring/loadtest/locust_files/client.py
This was an artifact that reappeared after rebasing and was not previously caught
=> Remove bad conf import

build/deploy/db_schemas/defaultdb.libsonnet
needed to update libsonnet for uploading the schemas to configmap
=> [deployment] Add missing schema update file

monitoring/prober/scd/test_subscription_update_validation.py, pkg/scd/models/subscriptions.go, pkg/scd/subscriptions_handler.go
This resolves https://github.com/interuss/dss/issues/386
1.Update Subscription now validates against all its dependentOperations in all 4 dimensions (2d, altitude range, time range)
2.HTTP 400 will be returned with the invalid dimension when improper update request is made
3.Added Prober test to capture all update subscription validation scenarios (both valid and invalid)
4.Tested through both docker_e2e and prober tests
=> [SCD #386] Implemented Subscription Update Validation against dpendentOperations

introduction_to_repository.md
Updated instructions for local debugging in README.
=> Using monitoring toolset for local debugging

introduction_to_repository.md
Added Instructions to run DSS locally
=> Readme module import update

monitoring/monitorlib/formatting.py, monitoring/monitorlib/scd.py, monitoring/monitorlib/testing.py, monitoring/prober/rid/test_isa_simple.py, monitoring/prober/rid/test_isa_simple_heavy_traffic_concurrent.py, monitoring/prober/rid/test_subscription_simple.py, monitoring/prober/scd/test_constraint_simple.py, monitoring/prober/scd/test_operation_simple.py, monitoring/prober/scd/test_operation_simple_heavy_traffic.py, monitoring/prober/scd/test_operation_simple_heavy_traffic_concurrent.py, monitoring/prober/scd/test_operations_simple.py, monitoring/prober/scd/test_subscription_simple.py, monitoring/prober/scd/test_subscription_update_validation.py
This PR fixes #510 so that automated tests should run correctly again.
=> [prober] Change all tests to compare datetimes the same way

monitoring/rid_qualifier/display_data_evaluator.py, monitoring/rid_qualifier/utils.py
Added a new test config reduce query variations, added to keep every third view box to be the same, refactor to have rect generation before observation
=> rid_qualifier: Reducing query variation in the display data evaluator

introduction_to_repository.md
Added note about the interfaces folder
=> [docs] Update introduction_to_repository.md

pkg/auth/auth.go, pkg/models/models.go, pkg/scd/constraints_handler.go, pkg/scd/errors/errors.go, pkg/scd/operational_intents_handler.go, pkg/scd/store/cockroach/constraints.go, pkg/scd/store/cockroach/operational_intents.go, pkg/scd/store/cockroach/store.go, pkg/scd/store/cockroach/subscriptions.go, pkg/scd/subscriptions_handler.go
This PR finalise the [SCD API interface work package](https://github.com/interuss/dss/wiki/Updating-SCD-API#interface). ​
Definition Of Done:
- `make lint` pass
=> [scd] Finalise update of SCD API interface 0.3.16

monitoring/prober/scd/test_constraint_simple.py, monitoring/prober/scd/test_operation_references_error_cases.py, monitoring/prober/scd/test_operation_references_state_transition.py, monitoring/prober/scd/test_operation_simple.py, monitoring/prober/scd/test_operation_special_cases.py, monitoring/prober/scd/test_operations_simple.py, monitoring/prober/scd/test_subscription_queries.py, monitoring/prober/scd/test_subscription_simple.py, monitoring/prober/scd/test_subscription_update_validation.py
#562 failed to recognize that some code was deleted on master and should be deleted on scd_api_update.  This PR fixes that oversight.
=> [scd] Fix previous merge from master to scd_api_update

pkg/scd/subscriptions_handler.go
=> [scd] Fix create subscription

monitoring/prober/scd/test_subscription_simple.py
=> [prober] Update test_subscription_simple to 0.3.17 API

monitoring/prober/scd/test_operation_simple_heavy_traffic.py
=> [prober] Update test_operation_simple_heavy_traffic to 0.3.17 API

monitoring/prober/scd/test_subscription_update_validation.py
=> [prober] Fix scd/test_subscription_update_validation

monitoring/prober/scd/test_operation_simple_heavy_traffic_concurrent.py
=> [prober] Update test_operation_simple_heavy_traffic_concurrent to 0.3.17 API

monitoring/prober/scd/test_operation_special_cases.py, monitoring/prober/scd/test_subscription_queries.py
This PR fixes #586 as well as issues in test_operation_special_cases.py.
=> [prober] Fix remaining tests for SCD API 0.3.17

README.md, README_DSS.md, concepts.md
This PR simplifies the main README and clarifies the content of the repository for visitors which may be interested in monitoring modules.
=> Main README refactoring

.github/workflows/uss-qualifier-tests.yml, monitoring/rid_qualifier/Makefile, monitoring/rid_qualifier/run_flight_data_generator.sh, monitoring/rid_qualifier/run_locally.sh, monitoring/rid_qualifier/scripts/docker-compose_qualifier_mocks.yaml, monitoring/rid_qualifier/scripts/test_docker.sh
Part of the effort to reorganize the qualifier to include other services (ie SCD), this PR automates the testing of the qualifier:
1. Starts the mock server
2. Runs the qualifier with the default configuration
The PR introduces Github Actions to run tests.
=> [monitoring] Test rid_qualifier with Github Actions

interfaces/automated-testing/scd/scd.yaml
This PR introduces the base OpenAPI file with a simple status endpoint.
=> [automated-testing/scd] Initial status endpoint

interfaces/automated-testing/scd/scd.yaml
> depends on #639
This PR adds authorization to the status endpoint.
=> [automated-testing/scd] Add Authorization

Makefile, build/deploy/metadata_base.libsonnet, build/dev/docker-compose_dss.yaml, test/docker_e2e.sh, test/migrations/clear_db.sh
=> [db] Move to CRDB 21.2.3

monitoring/uss_qualifier/common_data_definitions.py, monitoring/uss_qualifier/rid/reports.py, monitoring/uss_qualifier/scd/data_interfaces.py
This PR introduces data structures for the interface between test executor and the simulator.
=> SCD Qualifier Simulator: Interface definitions between test executor and simulator

build/deploy/db_schemas/scd/downfrom-v1.0.0-remove_initial_version.sql, build/deploy/db_schemas/scd/downfrom-v2.0.0-remove_api_1_0_0_support.sql, build/deploy/db_schemas/scd/downfrom-v3.0.0-remove_inverted_indices.sql, build/deploy/db_schemas/scd/downfrom-v3.1.0-remove_uss_availability.sql, build/dev/check_scd_constraints.sh, build/dev/check_scd_operations.sh, build/dev/check_scd_subscriptions.sh, build/dev/check_scd_write.sh, test/migrations/migrate_db.sh
downfrom* scripts have been tested by running following commands in sequence:
```
test/migrations/clear_db.sh
test/migrations/migrate_db.sh scd latest
test/migrations/migrate_db.sh scd <older-version>
```
example:
`test/migrations/migrate_db.sh scd 2.0.0`
=> [crdb/schemas] Update SCD DB down migrate scripts.

monitoring/mock_uss/run_locally_scdsc.sh, monitoring/monitorlib/clients/scd_automated_testing.py, monitoring/uss_qualifier/.gitignore, monitoring/uss_qualifier/Dockerfile, monitoring/uss_qualifier/main.py, monitoring/uss_qualifier/run_locally_scd.sh, monitoring/uss_qualifier/scd/data_interfaces.py, monitoring/uss_qualifier/scd/executor/errors.py, monitoring/uss_qualifier/scd/executor/executor.py, monitoring/uss_qualifier/scd/executor/report_recorder.py, monitoring/uss_qualifier/scd/executor/runner.py, monitoring/uss_qualifier/scd/executor/target.py, monitoring/uss_qualifier/scd/reports.py
This PR adds the following improvement to the uss qualifier scd component:
1. Capture of interactions and issues in the test runner 
2. Generation a single report per invocation of the SCD part of uss_qualifier (`report_scd.json`)
3. Adds qualifier_scd version to the report using `uss_qualifier_scd` as release component name.
=> [uss_qualifier/scd] report

monitoring/uss_qualifier/common_data_definitions.py
This PR implements suggested changes in Severity options discussed [here](https://github.com/interuss/dss/pull/717#discussion_r812293117).
=> [uss_qualifier] Update Severity content

pkg/cockroach/cockroach.go, pkg/cockroach/cockroach_test.go
This PR fixes issue #732 .
The following keys were not passed as expected when trying to connect to the cluster with ssl mode enabled:
- sslrootcert
- sslcert
- sslkey
=> [dss] fix issue #732

monitoring/monitorlib/requirements.txt
=> [monitoring] Fix #745

monitoring/mock_uss/run_locally_riddp.sh, monitoring/mock_uss/run_locally_ridsp.sh
This PR fixes the issue when `run_locally_ridddp.sh` and `run_locally_ridsp.sh` is run. Without these fixes I am getting a error attached below.
=> [mock_uss] Fixes for Mock USS / RID run_locally

monitoring/uss_qualifier/.gitignore, monitoring/uss_qualifier/bin/generate_scd_test_definition.sh, monitoring/uss_qualifier/scd/simulator/README.md, monitoring/uss_qualifier/scd/simulator/main.py, monitoring/uss_qualifier/scd/simulator/test_definitions/astm_strategic_coordination/nominal_planning.py, monitoring/uss_qualifier/scd/simulator/test_definitions/astm_strategic_coordination/test_nominal_planning.py, monitoring/uss_qualifier/scd/simulator/test_definitions/builder.py
This PR proposes a first structure to breakdown the work of PR #685. Currently it simply generates the exact copy of `scd/test_definitions/CHE/astm-strategic-coordination/nominal-planning-1.json` as a first example.
Run: 
```
bin/generate_scd_test_definition.sh CHE
```
Test:
```
PYTHONPATH=$(pwd)/../../../.. pytest
```
=> [uss_qualifier/scd/simulator] Initial canvas to breakdown PR #685

monitoring/uss_qualifier/webapp/forms.py, monitoring/uss_qualifier/webapp/routes.py, monitoring/uss_qualifier/webapp/tasks.py, monitoring/uss_qualifier/webapp/templates/tests.html
This PR is a cleaned version of PR: #768
=> [uss_qualifier/webapp] Replace webapp routes with open api endpoints

README.md
This PR cleans up some of the references and wording in the main README to reflect the current status of a number of things (e.g., F3411-22 being published, F3548-21 being published, new ASTM links).
=> [docs] Clean up main README

interfaces/automated-testing/geo-awareness/design/CHE/README.md, interfaces/automated-testing/geo-awareness/design/CHE/geo-awareness-che-1.json
This PR adds the test scenario created in the [SUSI Technical Working Group](https://susi.swiss) by Tim to check compliance of Geo-Awareness services.
See README for details.
=> [automated-testing/geo-awareness] Add CHE test scenario

.github/workflows/monitoring-tests.yml, monitoring/mock_uss/Makefile, monitoring/mock_uss/__init__.py, monitoring/mock_uss/auth.py, monitoring/mock_uss/config.py, monitoring/mock_uss/mockuss.py, monitoring/mock_uss/resources.py, monitoring/mock_uss/riddp/behavior.py, monitoring/mock_uss/riddp/clustering.py, monitoring/mock_uss/riddp/database.py, monitoring/mock_uss/riddp/routes.py, monitoring/mock_uss/riddp/routes_behavior.py, monitoring/mock_uss/riddp/routes_observation.py, monitoring/mock_uss/ridsp/behavior.py, monitoring/mock_uss/ridsp/database.py, monitoring/mock_uss/ridsp/routes.py, monitoring/mock_uss/ridsp/routes_behavior.py, monitoring/mock_uss/ridsp/routes_injection.py, monitoring/mock_uss/ridsp/routes_ridsp.py, monitoring/mock_uss/routes.py, monitoring/mock_uss/scdsc/database.py, monitoring/mock_uss/scdsc/routes.py, monitoring/mock_uss/scdsc/routes_injection.py, monitoring/mock_uss/scdsc/routes_scdsc.py
This PR adds :
1. a Makefile to lint and format the `monitoring/mock_uss` project
2. Rename USS Qualifier tests to Monitoring projects tests (python) and adds a step to cover mock_uss.
3. Format the code of `mock_uss`.
Due to the formatting of the package, the PR is pretty large. See first commit for points 1 and 2. The second commit is the result of make format.
=> [python] Format mock_uss

.github/workflows/monitoring-tests.yml, monitoring/monitorlib/Makefile, monitoring/monitorlib/auth.py, monitoring/monitorlib/auth_validation.py, monitoring/monitorlib/clients/scd.py, monitoring/monitorlib/clients/scd_automated_testing.py, monitoring/monitorlib/fetch/__init__.py, monitoring/monitorlib/fetch/rid.py, monitoring/monitorlib/fetch/scd.py, monitoring/monitorlib/fetch/summarize.py, monitoring/monitorlib/formats.py, monitoring/monitorlib/formatting.py, monitoring/monitorlib/geo.py, monitoring/monitorlib/ids.py, monitoring/monitorlib/infrastructure.py, monitoring/monitorlib/locality.py, monitoring/monitorlib/multiprocessing.py, monitoring/monitorlib/mutate/rid.py, monitoring/monitorlib/mutate/scd.py, monitoring/monitorlib/rid.py, monitoring/monitorlib/rid_automated_testing/injection_api.py, monitoring/monitorlib/rid_automated_testing/observation_api.py, monitoring/monitorlib/rid_v2.py, monitoring/monitorlib/scd.py, monitoring/monitorlib/scd_automated_testing/scd_injection_api.py, monitoring/monitorlib/testing.py, monitoring/monitorlib/versioning.py
Similarly to #823, This PR adds :
- a Makefile to lint and format the monitoring/monitorlib package
- a step to cover monitorlib.
- Format the code of monitorlib.
Due to the formatting of the package, the PR is pretty large. See first commit for points 1 and 2. The second commit is the result of make format.
=> [python] Format monitorlib

build/README.md, build/deploy/examples/minimum/main.jsonnet, build/deploy/metadata_base.libsonnet, build/deploy/prometheus.libsonnet
similarly to https://github.com/interuss/dss/pull/845 , make the prometheus storage class configurable
=> [tanka][prometheus] prometheus storage class

monitoring/uss_qualifier/main.py, monitoring/uss_qualifier/reports/report.py
This PR adds the codebase version used to run uss_qualifier to the report.
=> [uss_qualifier] Include codebase version in uss_qualifier report

interfaces/README.md
Kicking off EasyCLA process with simple commit/PR.
This is a non-functional commit to see if a bot tells me to get EasyCLA signed.
OK to reject if desired after I get through that EasyCLA process, though READMEs are cool.
=> Created README for Interfaces dir.

monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py, monitoring/uss_qualifier/scenarios/astm/netrid/injected_flight_collection.py, monitoring/uss_qualifier/scenarios/astm/netrid/nominal_behavior.py, monitoring/uss_qualifier/scenarios/astm/netrid/virtual_observer.py
Currently, uss_qualifier contains a large, monolithic display_data_evaluator from the first draft of the first automated tests.  This monolithic structure makes it difficult to improve upon the functionality of the RID nominal behavior scenario it supports.  This PR simply refactors that monolith into multiple pieces to make future improvements to the scenario (and other scenarios which might reuse it) easier.  No changes in functionality are intended.
=> [uss_qualifier] Refactor RID nominal behavior scenario

monitoring/mock_uss/geoawareness/routes_geoawareness_test.py
This fixes the build break trickily introduced by #875
=> [bug] Pin geo-awareness dataset source URL

Dockerfile, build/README.md, build/deploy/db_schemas/scd.libsonnet, monitoring/prober/rid/v2/test_subscription_validation.py, monitoring/prober/scd/test_operation_references_error_cases.py
When performing a full Google Cloud DSS deployment from scratch to test #905, I discovered a few pre-existing deployment issues that needed to be addressed.  This PR contains the fixes I found necessary to successfully deploy the DSS in #905 and successfully complete a prober run on the deployed DSS.
=> [deployment] Fix deployment issues

Makefile, build/dev/check_dss.sh, build/dev/check_scd_clear.sh, build/dev/check_scd_write.sh, build/dev/check_subs.sh, build/dev/extract_json_field.py, build/dev/read_scd_constraint_reference.sh, build/dev/read_scd_operational_intent_reference.sh, build/dev/read_scd_subscription.sh
To update #905 with changes from #909
=> #822 gRPC layer removal: merge latest developments from master 

monitoring/uss_qualifier/common_data_definitions.py, monitoring/uss_qualifier/reports/report.py, monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py, monitoring/uss_qualifier/scenarios/astm/netrid/nominal_behavior.py, monitoring/uss_qualifier/scenarios/scenario.py, monitoring/uss_qualifier/suites/suite.py
This PR refines documentation and expectations for Severity level when recording failed checks.  Specifically, High Severity issues result in gracefully stopping the current test scenario (but allowing the test run to proceed), and Critical Severity issues result in gracefully stopping the entire test run (new behavior in this PR).  Medium Severity indicates a requirement violation but the test can continue, and Low Severity indicates a possible improvement but not a requirements violation.
Suggestions for alternate meanings or approaches are welcome.
=> [uss_qualifier] Clarify Severity expectations

monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss_interoperability.py, monitoring/uss_qualifier/scenarios/scenario.py
Fixes #928.
Also throws in some error message formatting to get the CI to re-evaluate the second commit.
=> [uss_qualifier] Fix time comparison in dss_interoperability

build/dev/probe_locally.sh, pkg/rid/models/api/v2/conversions.go, test/migrations/rid_db_post_migration_e2e.sh
=> [bug/F3411-22a] Fix F3411-22a altitude reference

pkg/scd/subscriptions_handler.go
This should fix #953. The issue was caused by the fact that the fields are pointers on slice, pointers were initialized but no slice was created with `make()` and the marshaller seemed to react weirdly to this. 
Side note: IMO this pointer on slice generated by `openapi-to-go-server` is not correct. This should just be a slice, which can be nil itself and be ignored by the marshaller if it is.
=> [bug] Fix #953

pkg/scd/operational_intents_handler.go
Reverts interuss/dss#1104 due to incorrect merge commit being used.
=> Revert "Squished commit (#1104)"

pkg/scd/operational_intents_handler.go
This is a rework of #1057 after most changes for #1088 have landed.
The DSS built from this PR successfully passed the new qualifier's implicit subscription handling scenario, although that scenario still needs to be extended to cover all corner cases.
The PR is open for review, as it addresses #1056
=> [scd] properly cleanup implicit sub on oir update

pkg/scd/operational_intents_handler.go
See for context https://github.com/interuss/dss/pull/1096#issuecomment-2326345564
cc/ @Shastick
=> [scd] Use scdmodels for OVN+VersionNumber and simplify 'version' variable flow

pkg/rid/models/api/v2/conversions.go, pkg/rid/server/v2/isa_handler.go
=> [dss] ridv2: group subscriptions to notify by their callback URL

pkg/rid/models/api/v1/conversions.go, pkg/rid/server/v1/isa_handler.go
=> [dss] ridv1: group subscriptions to notify by their callback URL

deploy/README.md
This PR fixes broken links on the /deploy/README.md document.
=> [docs] Fix broken links
